CORE = xc

VSRC = address.v cheat.v dac.v dcm.v main.v mcu_cmd.v msu.v sd_dma.v spi.v \
       xc_top.v xc_soc.v xc_m0.v xc_cache.v xc_bridge.v xc_window.v xc_stream.v xc_decbox.v xc_brr.v xc_tick.v
VHSRC =

HEADER = config.vh

COMMON_IP = dac_buf msu_databuf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ip/mk2

INT_IP = pll

include ../settings.mk
include ../common.mk

