"""French strings for the sd2snes menu.

Maps const.a65 string labels -> fr text. Accented chars are written as
real UTF-8 here; build_const.py encodes them to the font byte codes.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
"""

TRANSLATIONS = {
    'text_clkset': 'Veuillez régler l\'heure',
    'text_mainmenu': 'Menu principal',
    'text_mm_file': 'Navigateur de fichiers',
    'text_mm_last': 'Jeux récents',
    'text_mm_favorites': 'Jeux favoris',
    # In-game TAB menu HELP tab (Phase 2)
    'text_igm_hdr_controls': 'COMMANDES EN JEU',
    'text_igm_open': 'Ouvrir menu:       L+R+Y+Gauche',
    'text_igm_save': 'Sauver savestate:  Start+R',
    'text_igm_load': 'Charger savestate: Start+L',
    'text_igm_slot': 'Choisir slot:      Select + D-Pad',
    'text_igm_reset': 'Vers menu:         L+R+Select+X',
    'text_igm_hdr_keys': 'TOUCHES DU MENU',
    'text_igm_tab': 'L / R:     onglet',
    'text_igm_page': 'Gauche/Droite: page',
    'text_igm_nav': 'Haut/Bas:   déplacer',
    'text_igm_act': 'A: valider   X: tous',
    'text_igm_close': 'B: fermer menu',
    'text_igm_note': 'Certains combos dans les Options',
    'text_igm_st_title': 'CHOISIR SLOT DE SAVESTATE',
    'text_igm_st_slot': 'SLOT',
    'text_igm_st_full': 'OCCUPE',
    'text_igm_st_empty': 'VIDE',
    'text_igm_st_hint': 'Start+R sauver   Start+L charger',
    'text_igm_st_disabled': 'Slots de savestate desactives',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'AIDE',
    'text_igm_tab_manual': 'GUIDES',
    'text_igm_tab_trainer': 'TRAINER',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    'text_igm_sv_title': 'SAUVEGARDE',
    'text_igm_sv_nosram': 'Ce jeu ne possede pas de sauvegarde pile',
    'text_igm_sv_file': 'Fichier .srm:',
    'text_igm_sv_exists': 'PRESENT',
    'text_igm_sv_missing': 'ABSENT',
    'text_igm_sv_size': 'Taille:',
    'text_igm_sv_write': 'Derniere:',
    'text_igm_sv_autosave': 'Auto-sauve.:',
    'text_igm_sv_on': 'ACTIVE',
    'text_igm_sv_off': 'INACTIF',
    'text_igm_sv_hint_on': 'La sauvegarde est ecrite automatiquement en jeu',
    'text_igm_sv_hint_off': 'Auto-sauve. inactif - sauvez depuis le menu',
    'text_igm_sv_slottitle': 'CHOISIR LE SLOT SRAM',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Actif au prochain lancement du jeu',
    'text_igm_mn_title': 'MANUEL DU JEU',
    'text_igm_mn_read': 'A: Lire le manuel',
    'text_igm_mn_pages': 'pages',
    'text_igm_mn_notfound': 'Manuel introuvable',
    'text_igm_mn_error': 'Erreur de chargement du manuel',
    'text_igm_mn_guide': 'GUIDE',
    'text_igm_mn_select': 'CHOISIR UN GUIDE',
    'text_igm_mn_keys1': 'A: zoom 2x   L/R: changer de page',
    'text_igm_mn_keys2': 'Croix: deplacer   B: retour',
    'text_igm_mn_slug_manual': 'Manuel',
    'text_igm_mn_slug_guide': 'Guide',
    'text_igm_mn_slug_map': 'Carte',
    'text_igm_mn_slug_insert': 'Encart',
    'text_igm_mn_slug_other': 'Autre',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'TRAINER RAM',
    'text_igm_tr_searchtype': 'Type de rech.:',
    'text_igm_tr_datatype': 'Taille:',
    'text_igm_tr_value': 'Valeur:',
    'text_igm_tr_candidates': 'Candidats:',
    'text_igm_tr_compare': 'Comparer:',
    'text_igm_tr_exact': 'Valeur exacte',
    'text_igm_tr_unknown': 'Inconnue',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Égale à',
    'text_igm_tr_ne': 'Différente',
    'text_igm_tr_changed': 'Changée',
    'text_igm_tr_unchanged': 'Inchangée',
    'text_igm_tr_increased': 'Augmentée',
    'text_igm_tr_decreased': 'Diminuée',
    'text_igm_tr_gt': 'Plus grand',
    'text_igm_tr_lt': 'Plus petit',
    'text_igm_tr_newsearch': 'NOUVELLE RECHERCHE',
    'text_igm_tr_filter': 'FILTRER',
    'text_igm_tr_results': 'RÉSULTATS',
    'text_igm_tr_reset': 'RÉINITIALISER',
    'text_igm_tr_address': 'ADRESSE',
    'text_igm_tr_current': 'ACTUELLE',
    'text_igm_tr_setvalue': 'ÉCRIRE LA VALEUR',
    'text_igm_tr_freeze': 'GELER',
    'text_igm_tr_unfreeze': 'DÉGELER',
    'text_igm_tr_addcheat': 'AJOUTER AUX CHEATS',
    'text_igm_tr_frozen': 'GELÉE',
    'text_igm_tr_searching': 'Recherche...',
    'text_igm_tr_noresults': 'Aucun résultat',
    'text_igm_tr_toomany': 'Trop de résultats - filtrez encore',
    'text_igm_tr_dropped_ss': 'Recherche annulée - state chargé',
    'text_igm_tr_dropped_rst': 'Recherche annulée - console reset',
    'text_igm_tr_nofreeze': 'Plus de place de cheat',
    'text_igm_tr_hint_setup': 'A: choisir   D-Pad: changer',
    'text_igm_tr_hint_edit': 'D-Pad: éditer   A: OK   B: sortir',
    'text_igm_tr_hint_list': 'A: inspecter   B: retour',
    'text_igm_tr_master_off': 'Master cheats OFF',
    'mtext_mm_cfg': 'Configuration',
    'mtext_mm_sysinfo': 'Informations système',
    'mtext_cfg_time': 'Régler l\'horloge',
    'mtext_cfg_ask_clock': "Demander l'heure au démarrage",
    'mtext_cfg_bsx': 'Paramètres BS-X',
    'mtext_cfg_browser': 'Paramètres du navigateur',
    'mtext_cfg_chip': 'Options des puces',
    'mtext_cfg_sgb': 'Paramètres SGB',
    'mtext_cfg_ingame': 'Paramètres en jeu',
    'mtext_cfg_savestates': 'Paramètres des savestates',
    'mtext_cfg_scic': 'Paramètres SuperCIC',
    'mtext_cfg_patch': 'Options de patch',
    'mtext_bsx_timesource': 'Horloge BS-X',
    'mtext_bsx_time': 'Heure personnalisée',
    'mtext_scic_enable': 'Activer le SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Mode vidéo du menu',
    'mtext_scic_vmode_game': ' {129}Mode vidéo du jeu',
    'mtext_scic_buscompat': 'Compat. timing bus',
    'mtext_browser_sort': 'Trier les dossiers',
    'mtext_browser_hide_ext': 'Masquer les extensions',
    'mtext_browser_msu_folders': 'Ouvrir dossiers MSU-1 comme jeu',
    'mtext_browser_sd2snes_dir': 'Afficher le dossier sd2snes',
    'mtext_browser_screensaver': 'Écran de veille',
    'mtext_browser_screensaver_timeout': 'Assombrir l\'écran après',
    'mtext_browser_ledbright': 'Luminosité des LED',
    'mtext_ingame_cheats': 'Cheats au démarrage',
    'mtext_ingame_shortreset': 'Reset vers le menu',
    'mtext_ingame_enable': 'Hook en jeu',
    'mtext_ingame_buttons': ' {129}Touches en jeu',
    'mtext_ingame_cheat_overlay': ' {129}Menu en jeu',
    'mtext_ingame_game_manual': ' {129}Manuel du jeu',
    'mtext_ingame_holdoff': ' {129}Délai initial',
    'mtext_ingame_savestate': 'Savestates en jeu',
    'mtext_savestate_slots': ' {129}Slot de la savestate',
    'mtext_loadstate_delay': ' {129}Délai de chargement (frames)',
    'mtext_sgb_enable_hooks': 'Hooks en jeu',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'Fonctionnalités SGB',
    'mtext_sgb_spr_increase': 'Limite max. de sprites (40)',
    'mtext_sgb_volume_boost': 'Amplification du volume',
    'mtext_sgb_clock': 'Horloge (Timing)',
    'mtext_sgb_bios': 'Version du BIOS',
    'mtext_ingame_regionpatch': 'Patch de région auto',
    'mtext_ingame_1chiptransientfixes': 'Correctifs transitoires 1CHIP',
    'mtext_ingame_brightlimit': 'Limite de luminosité',
    'mtext_ingame_resetpatch': 'Patch de reset pour la phase d\'horloge',
    'mtext_ingame_autosave': 'Sauvegarde auto',
    'mtext_ingame_autosave_msu1': ' {129}Sauvegarde auto MSU-1',
    'mtext_chip_cx4_speed': 'Vitesse Cx4',
    'mtext_chip_cc_time_limit': "Timer du Competition Cart (min)",
    'mtext_chip_gsu_speed': 'Vitesse SuperFX',
    'mtext_chip_msu1_volume_boost': 'Amplification du volume MSU-1',
    'mtext_a26_width': 'Largeur vidéo Atari 2600',
    'mdesc_mm_last': 'Afficher jusqu\'à 10 jeux récemment joués',
    'mdesc_mm_favorites': 'Afficher jusqu\'à 20 jeux favoris',
    'mdesc_mm_cfg': 'Configurer le sd2snes',
    'mdesc_mm_sysinfo': 'Infos sur version FW, carte SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Régler la date et l\'heure',
    'mdesc_cfg_ask_clock': "Demande l'heure au démarrage tant que l'horloge est non réglée",
    'mdesc_cfg_bsx': 'Paramètres spécifiques au BS-X/Satellaview',
    'mdesc_cfg_browser': 'Modifier les paramètres du navigateur de fichiers',
    'mdesc_cfg_chip': 'Définir les fonctionnalités des puces spéciales',
    'mdesc_cfg_ingame': 'Définir les fonctionnalités en jeu',
    'mdesc_cfg_sgb': 'Définir les fonctionnalités du Super Game Boy',
    'mdesc_cfg_savestates': 'Définir les fonctionnalités des savestates',
    'mdesc_cfg_scic': 'Activer/Désactiver le SuperCIC et définir les modes vidéo',
    'mdesc_cfg_patch': 'Options pour le soft-patching IPS/BPS',
    'mdesc_bsx_timesource': 'Choisir la date et l\'heure que voient les jeux BS-X',
    'mdesc_bsx_time': 'Définir une date et heure personnalisées pour les jeux BS-X',
    'mdesc_scic_enable': 'Requis pour les fonctionnalités améliorées du SuperCIC',
    'mdesc_scic_vmode_menu': 'Définir le mode vidéo pour le menu',
    'mdesc_scic_vmode_game': 'Définir le mode vidéo pour les jeux',
    'mdesc_scic_buscompat': 'Timing de bus étroit pour consoles où des jeux plantent ou ont des glitchs. Activez seulement si vous voyez des blocages.',
    'mdesc_browser_sort': 'Choisir de trier ou non les listes de fichiers',
    'mdesc_browser_hide_ext': 'Choisir de masquer ou non les extensions de fichiers',
    'mdesc_browser_msu_folders': 'A sur un dossier avec une seule ROM MSU-1 ouvre le jeu',
    'mdesc_browser_sd2snes_dir': 'Affiche /sd2snes dans la liste',
    'mdesc_browser_screensaver': 'Assombrir l\'écran après un certain temps',
    'mdesc_browser_screensaver_timeout': 'Définir le délai avant d\'assombrir l\'écran',
    'mdesc_browser_ledbright': 'Modifier la luminosité des LED',
    'mdesc_ingame_cheats': 'Démarrer ou non avec les cheats activés. Peut être modifié via les touches en jeu',
    'mdesc_ingame_shortreset': 'Où mène un reset. Dossier/ROM rouvrent le dossier du dernier jeu. Durée : appui court relance le jeu, long va à la ROM.',
    'mdesc_ingame_enable': 'Requis pour les touches en jeu et les cheats 7E/7F',
    'mdesc_ingame_buttons': 'Activer les touches en jeu (reset, active/désactive les cheats{127}{128}). Nécessite le hook en jeu.',
    'mdesc_ingame_cheat_overlay': 'Menu en jeu (maintenir L+R+Y+Gauche) : cheats, savestates, saves et guides. Nécessite le hook. Indisponible sur quelques puces spéciales.',
    'mdesc_ingame_game_manual': 'Affiche le manuel du jeu dans le menu en jeu. Necessite <rom>.man dans /sd2snes/info.',
    'mdesc_ingame_holdoff': 'Attendre 10 secondes avant d\'activer le hook (aide certains jeux à démarrer)',
    'mdesc_ingame_savestate': 'Activer les savestates en jeu et choisir la manette. Par défaut : Sauvegarder - Start+R / Charger - Start+L',
    'mdesc_savestate_slots': 'Activer les emplacements de savestate. Select+Dpad : chaque direction est un emplacement',
    'mdesc_loadstate_delay': 'Ajuster le délai de chargement de la savestate (frames)',
    'mdesc_sgb_enable_hooks': 'Requis pour les touches en jeu',
    'mdesc_sgb_enable_state': 'Activer les savestates intégrées sur SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Désactiver/activer les améliorations SGB',
    'mdesc_sgb_spr_increase': 'Augmenter le nombre de sprites visibles pris en charge',
    'mdesc_sgb_volume_boost': 'Ajuster l\'amplification du volume audio SGB s\'il est trop faible',
    'mdesc_sgb_clock': 'Ajuste l\'horloge SGB (timing)',
    'mdesc_sgb_bios': 'Sélectionner une version de firmware/BIOS SGB',
    'mdesc_ingame_regionpatch': 'Contourner la protection de région simple des jeux',
    'mdesc_ingame_1chiptransientfixes': 'Corriger les variations de luminosité pour réparer les bugs de synchro, fondus de scanlines et ombres manquantes sur consoles 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limiter la luminosité globale (ex : sur consoles 1CHIP pour respecter les niveaux RVB)',
    'mdesc_ingame_resetpatch': 'Activer le patch de reset pour synchroniser les horloges. Corrige les bugs graphiques de certains jeux',
    'mdesc_ingame_autosave': 'Sauvegarder automatiquement le fichier SRM quand la Save RAM change',
    'mdesc_ingame_autosave_msu1': 'MSU-1 : Saisit des opportunités pour auto-sauvegarder le fichier SRM. Peut causer de brèves saccades.',
    'mdesc_chip_cx4_speed': 'Définir la vitesse du coeur Cx4',
    'mdesc_chip_cc_time_limit': "Minuteur de manche des cartouches d'événement (Campus Challenge '92, PowerFest '94)",
    'mdesc_chip_gsu_speed': 'Définir la vitesse du coeur SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Ajuster l\'amplification du volume audio MSU1 si le sd2snes est trop silencieux (Rév. E-G)',
    'mdesc_a26_width': 'Largeur d\'image Atari 2600 : 160 est native 1:1, 256 remplit l\'écran',
    'mdesc_cx4_speed_fast': 'Exécuter aussi vite que possible',
    'mdesc_cx4_speed_normal': 'Exécuter à la vitesse d\'origine approx.',
    'mdesc_gsu_speed_fast': 'Exécuter aussi vite que possible',
    'mdesc_gsu_speed_normal': 'Exécuter à la vitesse d\'origine approx.',
    'text_filesel_selected_file': 'Fichier sélectionné',
    'text_filesel_context_add_to_favorites': 'Ajouter aux favoris',
    'mdesc_filesel_context_add_to_favorites': 'Ajouter le fichier sélectionné aux favoris',
    'text_filesel_context_remove_from_favorites': 'Retirer des favoris',
    'mdesc_filesel_context_remove_from_favorites': 'Retirer le fichier sélectionné des favoris',
    'text_recent_context_remove_from_recent': 'Retirer des jeux récents',
    'mdesc_recent_context_remove_from_recent': 'Retirer le fichier sélectionné de la liste des jeux récents',
    'text_filesel_set_as_autoboot': 'Définir comme démarrage auto',
    'mdesc_filesel_set_as_autoboot': 'Lancer cette ROM automatiquement au prochain allumage (maintenir START au démarrage/reset pour annuler)',
    'text_filesel_set_as_bgm': 'Définir comme musique de menu',
    'mdesc_filesel_set_as_bgm': 'Utiliser ce fichier SPC comme musique de fond du menu',
    'text_filesel_context_delete_file': 'Supprimer',
    'mdesc_filesel_context_delete_file': 'Supprimer le fichier sélectionné',
    'text_filesel_context_delete_srm': 'Supprimer le fichier de sauvegarde',
    'mdesc_filesel_context_delete_srm': 'Supprimer le fichier de sauvegarde SRM pour cette ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': "Voir, activer ou désactiver les cheats depuis le fichier YAML de cette ROM",
    'text_filesel_context_gameinfo': 'Infos du jeu',
    'mdesc_filesel_context_gameinfo': "Afficher la jaquette, la capture d'écran et les infos de ce jeu avant de jouer",
    'text_cheat_yes': 'Oui ',
    'text_cheat_no': 'Non ',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Nom',
    'text_cheat_none_msg': 'Aucun cheat trouvé pour cette ROM',
    'text_confirm_delete_file': 'Supprimer ce fichier ?',
    'text_confirm_delete_srm': 'Supprimer le fichier de sauvegarde ?',
    'text_confirm_hint': 'A:Confirmer B:Annuler',
    'text_confirm_no_sel': '[Non]',
    'text_confirm_no_unsel': ' Non ',
    'text_confirm_yes_sel': '[Oui]',
    'text_confirm_yes_unsel': ' Oui ',
    'text_statusbar_play': 'A:Jouer B:Retour X:Menu',
    'text_statusbar_keys': 'A:Sélect. B:Retour X:Menu Y:Contexte',
    'text_statusbar_spc': 'B:Retour',
    'text_statusbar_menu': 'A:Sélect. B:Retour',
    'text_last': 'Jeux récents',
    'text_favorite': 'Jeux favoris',
    'text_no_last': 'Aucun jeu récent',
    'text_no_favorite': 'Aucun jeu favori',
    'text_favorites_full': 'Liste des favoris pleine',
    'text_err_supplfile': 'Fichier requis manquant:',
    'text_err_noimpl': 'Puce non prise en charge :',
    'text_err_nohw': 'Matériel Mk.III requis :',
    'text_err_generic': 'Erreur de chargement :',
    'text_on_p1': 'On: J1',
    'text_on_p2': 'On: J2',
    'text_on': 'On',
    'text_off': 'Off',
    'text_15_max': '15 (max)',
    'text_theme': 'Thème',
    'text_cover_large': 'Grand',
    'text_cover_small': 'Petit',
    'text_gameinfo_context': 'Contexte',
    'text_nav_folder': 'Dossier',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Durée',
    'text_enabled': 'Activé',
    'text_disabled': 'Désactivé',
    'text_normal': 'Normal',
    'text_fast': 'Rapide',
    'text_a26_w256': '256 (large)',
    'text_rtc': 'Temps réel',
    'text_custom': 'Perso.',
    'text_yes': 'Oui',
    'text_no': 'Non',
    'text_auto': 'Auto',
    'text_add': 'Ajouter',
    'text_remove': 'Retirer',
    'text_edit': 'Modifier',
    'text_save': 'Sauver',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 heure',
    'text_spcplay': 'Lecteur audio SPC',
    'text_spcload': 'Chargement des données SPC vers le SPC700{127}{128}',
    'text_spcstarta': '**** Lecture du morceau SPC ****',
    'text_spcstartb': 'Nom :  ',
    'text_spcstartc': 'Titre : ',
    'text_spcstartd': 'Artiste :',
    'text_spc_statusbar': 'B:Retour',
    'text_loading': 'Chargement{127}{128}                     ',
    'text_saving': 'Sauvegarde{127}{128}                     ',
    # Window title prefix for the cheat list, composed by the menu. "Cheats" is kept
    # as-is in every language on purpose; only the preposition is localized.
    'text_cheat': 'Cheats pour ',
    'text_cheat_noname': '(sans nom)',
    'text_igm_cheat_noname': '(sans nom)',
    'text_igm_ch_none': 'Aucun cheat',
    'text_igm_ft_tab': '<>:ONGLET L/R:EXTREMITES A:OUVRIR B:FERMER',
    'text_igm_ft_cheats': 'A:ON/OFF Y:EDITER SEL:NOUVEAU X:CHEATS B:RETOUR',
    'text_igm_ft_generic': 'A:CHOISIR B:RETOUR',
    'text_igm_master_on': 'CHEATS: ON',
    'text_igm_master_off': 'CHEATS: OFF',
    'text_igm_ft_ce_edit': 'A:EDITER SEL:+CODE Y:RETIRER B:RETOUR',
    'text_igm_ft_ce_kbd': 'A:TAPER Y:EFFACER SEL:ESPACE X:OK B:ANNULER',
    'text_igm_ce_title_new': 'NOUVEAU CHEAT',
    'text_igm_ce_title_edit': 'MODIFIER LE CHEAT',
    'text_igm_ce_name': 'Nom:',
    'text_igm_ce_save': 'SAUVER',
    'text_igm_ce_delete': 'SUPPRIMER LE CHEAT',
    'text_igm_ce_confirm': 'Supprimer ce cheat ?',
    'text_igm_ce_confirm_keys': 'A: oui   B: non',
    'text_igm_ce_nosup': 'Mettez à jour le firmware',
    'text_igm_ce_full': 'La liste de cheats est pleine',
    'text_igm_ce_badcode': 'Code invalide',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Version firmware: {2}',
    'text_si_busy': "Calcul de l'espace disque{127}{128}",
    'text_si_removed': '  *** Carte SD retirée/USB occupé ***',
    'text_si_maker': 'Fabricant SD:    0x{3}, {34}{4}{34}',
    'text_si_product': 'Nom du produit: {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'Série SD:        {8}, Fab. {9}/{10}',
    'text_si_acc': 'Accès SD:     {11}.{12} / {13}.{14} ms moy/max',
    'text_si_accmeas': 'Accès SD:     mesure{127}{128}',
    'text_si_usage': 'Usage SD:   {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'lecture{127}{128}',
    'text_si_sgb_missing': 'absent',
    'text_si_sgb_mismatch': 'différent',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'Etat CIC: {19}',
    'text_si_clk': 'Horloge SNES: {20}Hz',
    'text_si_clkmeas': 'Horloge SNES: mesure{127}{128}',
    'text_si_u16on': 'Ultra16 série {21} (Autoboot On)',
    'text_si_u16off': 'Ultra16 série {21} (Autoboot Off)',
    'text_si_model': 'Modèle: {22}',
    'text_si_updatefw': '*** Mettez le firmware à jour ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Test mémoire',
    'mdesc_mm_memtest': 'Vérifie les liaisons FPGA-RAM (10 s). Le test complet vérifie chaque cellule (30 s). Redémarre.',
    'text_mtl_prompt': 'A: Lignes  X: Complet  B: Fermer',
    'text_mtl_prompt2': 'Les deux redémarrent. X prend 30s.',
    'text_mtl_run': 'Test de la mémoire, patientez{127}{128}',
    'text_mtl_none': 'Aucun test effectué.',
    'text_mtl_pass': 'Toutes les lignes RAM OK.',
    'text_mtl_fail': 'Défauts trouvés :',
    'text_mtl_nocore': '/sd2snes/fpga_test absent/invalide.',
    'text_mtl_more': '(autres défauts non affichés)',
    'text_mtl_cellpass': 'Toutes les cellules vérifiées.',
    'text_mtl_cellfail': 'Première cellule mauvaise en 0x',
    'text_mtl_cellskip': 'Scan ignoré : corrigez les lignes.',
    'text_mt_data': 'ligne de données D à vérifier',
    'text_mt_addr': "ligne d'adresse A à vérifier",
    'text_mt_short': 'court-circuit possible A',
    'text_mt_bytesel': 'LB# / UB# à vérifier',
    'text_mt_ctrl': 'CE# / OE# / WE# à vérifier',
    'text_mt_fpgactrl': 'CE#/OE#/WE# du FPGA à vérifier',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'Lecteur PCM',
    'text_pcm_prompt': 'A: Lecture/Pause   B: Fermer',
    'text_pcm_promptb': 'B: Fermer',
    'text_pcm_paused': 'En pause',
    'text_pcm_erropen': 'Impossible de lire ce fichier.',
    'text_pcm_errmagic': "Ce n'est pas un fichier PCM MSU-1.",
    'text_pcm_nosup': '*** Mettez le firmware à jour ***',
    'text_st_slotb_title': 'Sufami Turbo - Port B',
    'text_st_slotb_footer': 'A:Jouer  B:Retour  <>:Page  LR:Debut/Fin',
    'text_st_slotb_none': '[Aucune cartouche en port B]',
    'text_ips_nopatch': '[Pas de patch]',
    'text_ips_header': 'Patches',
    'mtext_patch_verify': 'Vérifier l\'intégrité (~23s)',
    'mtext_patch_clearppu': 'Effacer le PPU au démarrage',
    'mdesc_patch_verify': 'Relire la ROM patchée pour la vérifier (chargement beaucoup plus lent)',
    'mdesc_patch_clearppu': 'Effacer VRAM/CGRAM/OAM avant le démarrage d\'une ROM patchée (romhacks sans init PPU)',
    'text_patch_hdr_auto': 'auto  ',
    'text_patch_hdr_on': 'en-tet',
    'text_patch_hdr_off': 'brut  ',
    'text_patch_footer': 'A:Jouer  Y:Plus  B:Retour  <>:Page  LR:Début/Fin',
    'text_patch_creating': 'Création de la ROM...',
    'text_err_patchexport': 'Échec écriture ROM',
    'text_patch_export_ok': 'ROM patchée créée',
    'text_patch_export_part': 'ROM ok, assets incomplets',
    'text_patch_export_exists': 'La ROM patchée existe déjà',
    'text_patch_hdrsel_auto': 'Auto (détecter)',
    'text_patch_hdrsel_on': 'Avec en-tête',
    'text_patch_hdrsel_off': 'Sans en-tête',
    'mtext_patch_header_mode': "Mode d'en-tête",
    'mdesc_patch_header_mode': 'Lecture des offsets IPS : Auto, En-tête (décale de 512 o) ou Brut.',
    'mtext_patch_create_rom': 'Créer une ROM patchée',
    'mdesc_patch_create_rom': "Écrit la ROM patchée à côté de l'originale, nommée d'après le fichier patch, en copiant jaquette, sauvegardes, codes et guides. Prend des minutes.",
    'cheat_tab_head': 'Description                              Activé',
    'cheat_tab_hint_text': ' A:On/Off Y:Editer Sel:Ajout B:Fin',
    'mtext_browser_showcov': 'Afficher les jaquettes',
    'mdesc_browser_showcov': 'Afficher les jaquettes des jeux dans le menu',
    'mtext_browser_covlists': ' {129}Favoris/Récents',
    'mdesc_browser_covlists': 'Afficher aussi les jaquettes dans les listes Récents et Favoris',
    'mtext_browser_menumusic': 'Musique du menu',
    'mtext_browser_menumusic_random': ' {129}Musique aléatoire',
    'mtext_browser_menusfx': 'Sons du menu',
    'mtext_browser_text_outline': 'Contour du texte',
    'mtext_browser_text_aa': 'Lissage du texte',
    'mdesc_browser_menumusic': 'Jouer la musique de fond (menu.spc) dans le menu',
    'mtext_browser_sortfav': 'Trier les favoris',
    'mdesc_browser_sortfav': 'Trier la liste des favoris par ordre alphabétique',
    'mtext_browser_restoretheme': 'Restaurer le thème',
    'mdesc_browser_restoretheme': 'Rétablir le thème par défaut du menu',
    'mtext_browser_restoreclassic': 'Restaurer le thème classique',
    'mdesc_browser_restoreclassic': "Charger l'apparence classique du sd2snes (nécessite /sd2snes/classic.thm sur la carte)",
    'mtext_browser_restoremusic': 'Restaurer la musique',
    'mdesc_browser_restoremusic': 'Rétablir la musique de fond par défaut (menu.spc)',
    'mdesc_browser_menumusic_random': 'Tire un .spc au hasard du dossier à chaque chargement',
    'mdesc_browser_text_outline': 'Contour sombre du texte du menu : suivre le thème, ou forcer',
    'mdesc_browser_text_aa': 'Bords lissés du texte du menu : suivre le thème, ou forcer',
    'text_mm_language': 'Langue',
    'mdesc_mm_language': 'Définir la langue du menu/firmware',
    'mdesc_browser_menusfx': 'Jouer des effets sonores lors de la navigation dans le menu',
    'mtext_browser_gameinfo': 'Infos du jeu avant lancement',
    'mtext_gameinfo_enable': 'Afficher l\'écran d\'infos',
    'mdesc_browser_gameinfo': 'Afficher la jaquette, la capture d\'écran et les infos avant de lancer une ROM ayant une entrée dans /sd2snes/info',
    'mdesc_cfg_gameinfo': 'Options de l\'écran d\'infos du jeu (avant lancement)',
    'mtext_browser_gameinfo_video': ' {129}Afficher la vidéo',
    'mdesc_browser_gameinfo_video': 'Lire le clip animé sur l\'écran d\'infos du jeu (désactivé affiche une capture statique)',
    'mtext_browser_gameinfo_music': ' {129}Jouer la musique de la vidéo',
    'mdesc_browser_gameinfo_music': 'Jouer la bande-son du clip pendant sa lecture. Nécessite Afficher la vidéo.',
    'text_gi_developer': 'Développeur',
    'text_gi_publisher': 'Éditeur',
    'text_gi_year': 'Année',
    'text_gi_players': 'Joueurs',
    'text_gi_genre': 'Genre',
    'text_gi_chip': 'Puce',
    'text_gi_footer': 'A: Jouer  B: Retour  Y: Description',
    'text_gi_footer_nav': 'A:Jouer B:Retour Y:Desc Haut/Bas:Jeu',
    'text_gi_footer_full': 'B: Retour  Haut/Bas: Défiler',
    'text_gi_footer_man': 'A: Jouer  B: Retour  Y: Description  X: Guides',
    'text_gi_footer_nav_man': 'A:Jouer B:Retour Y:Desc X:Guides Haut/Bas:Jeu',
    'text_gi_footer_pick': 'A: Ouvrir  B: Retour',
    'text_gi_slug_manual': 'Manuel',
    'text_gi_slug_guide': 'Guide',
    'text_gi_slug_map': 'Carte',
    'text_gi_slug_insert': 'Encart',
    'text_gi_slug_other': 'Autre',
}
