"""Brazilian Portuguese strings for the sd2snes menu.

Maps const.a65 string labels -> pt-BR text. Accented chars are written as
real UTF-8 here; build_const.py encodes them to the font byte codes.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
"""

TRANSLATIONS = {
    'text_clkset': 'Ajuste a hora',
    'text_mainmenu': 'Menu Principal',
    'text_mm_file': 'Navegador de Arquivos',
    'text_mm_last': 'Jogos Recentes',
    'text_mm_favorites': 'Jogos Favoritos',
    # In-game TAB menu HELP tab (Phase 2)
    'text_igm_hdr_controls': 'CONTROLES NO JOGO',
    'text_igm_open': 'Abrir menu:         L+R+Y+Esq',
    'text_igm_save': 'Salvar savestate:   Start+R',
    'text_igm_load': 'Carregar savestate: Start+L',
    'text_igm_slot': 'Escolher slot:      Select + D-Pad',
    'text_igm_reset': 'Reset p/ menu:      L+R+Select+X',
    'text_igm_hdr_keys': 'TECLAS DO MENU',
    'text_igm_tab': 'L / R:     troca aba',
    'text_igm_page': 'Esq/Dir:   muda página',
    'text_igm_nav': 'Cima/Baixo: mover',
    'text_igm_act': 'A: aplicar   X: todos',
    'text_igm_close': 'B: fechar menu',
    'text_igm_note': 'Alguns combos ajustáveis nas Opções',
    'text_igm_st_title': 'ESCOLHER SLOT DE SAVESTATE',
    'text_igm_st_slot': 'SLOT',
    'text_igm_st_full': 'OCUPADO',
    'text_igm_st_empty': 'VAZIO',
    'text_igm_st_hint': 'Start+R salva   Start+L carrega',
    'text_igm_st_disabled': 'Slots de savestate desativados',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'AJUDA',
    'text_igm_tab_manual': 'GUIAS',
    'text_igm_tab_trainer': 'TREINADOR',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    'text_igm_sv_title': 'SAVE DO JOGO',
    'text_igm_sv_nosram': 'Este jogo não tem save de bateria',
    'text_igm_sv_file': 'Arquivo .srm:',
    'text_igm_sv_exists': 'EXISTE',
    'text_igm_sv_missing': 'NÃO EXISTE',
    'text_igm_sv_size': 'Tamanho:',
    'text_igm_sv_write': 'Última grav.:',
    'text_igm_sv_autosave': 'Autosave:',
    'text_igm_sv_on': 'LIGADO',
    'text_igm_sv_off': 'DESLIGADO',
    'text_igm_sv_hint_on': 'O save é gravado automaticamente durante o jogo',
    'text_igm_sv_hint_off': 'Autosave desligado - salve pelo menu do jogo',
    'text_igm_sv_slottitle': 'ESCOLHA O SLOT DE SRAM',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Vale no próximo boot do jogo',
    'text_igm_mn_title': 'MANUAL DO JOGO',
    'text_igm_mn_read': 'A: Ler o manual',
    'text_igm_mn_pages': 'páginas',
    'text_igm_mn_notfound': 'Manual não encontrado',
    'text_igm_mn_error': 'Erro ao carregar o manual',
    'text_igm_mn_guide': 'GUIA',
    'text_igm_mn_select': 'SELECIONE UM GUIA',
    'text_igm_mn_keys1': 'A: zoom 2x   L/R: muda pagina',
    'text_igm_mn_keys2': 'Direcional: mover   B: voltar',
    'text_igm_mn_slug_manual': 'Manual',
    'text_igm_mn_slug_guide': 'Guia',
    'text_igm_mn_slug_map': 'Mapa',
    'text_igm_mn_slug_insert': 'Encarte',
    'text_igm_mn_slug_other': 'Outro',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'TREINADOR DE RAM',
    'text_igm_tr_searchtype': 'Tipo de busca:',
    'text_igm_tr_datatype': 'Tamanho:',
    'text_igm_tr_value': 'Valor:',
    'text_igm_tr_candidates': 'Candidatos:',
    'text_igm_tr_compare': 'Comparar:',
    'text_igm_tr_exact': 'Valor exato',
    'text_igm_tr_unknown': 'Desconhecido',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Igual a',
    'text_igm_tr_ne': 'Diferente',
    'text_igm_tr_changed': 'Mudou',
    'text_igm_tr_unchanged': 'Não mudou',
    'text_igm_tr_increased': 'Aumentou',
    'text_igm_tr_decreased': 'Diminuiu',
    'text_igm_tr_gt': 'Maior que',
    'text_igm_tr_lt': 'Menor que',
    'text_igm_tr_newsearch': 'NOVA BUSCA',
    'text_igm_tr_filter': 'FILTRAR',
    'text_igm_tr_results': 'RESULTADOS',
    'text_igm_tr_reset': 'REINICIAR BUSCA',
    'text_igm_tr_address': 'ENDEREÇO',
    'text_igm_tr_current': 'ATUAL',
    'text_igm_tr_setvalue': 'GRAVAR VALOR',
    'text_igm_tr_freeze': 'CONGELAR',
    'text_igm_tr_unfreeze': 'DESCONGELAR',
    'text_igm_tr_savecheat': 'SALVAR CHEAT',
    'text_igm_tr_frozen': 'CONGELADO',
    'text_igm_tr_searching': 'Buscando...',
    'text_igm_tr_noresults': 'Nenhum resultado',
    'text_igm_tr_toomany': 'Resultados demais - filtre de novo',
    'text_igm_tr_dropped_rst': 'Busca reiniciada - console resetado',
    'text_igm_tr_nofreeze': 'Máximo de 4 congelados',
    'text_igm_tr_hint_setup': 'A: escolher   D-Pad: mudar',
    'text_igm_tr_hint_edit': 'D-Pad: editar   A: OK   B: sair',
    'text_igm_tr_hint_list': 'A: inspecionar   B: voltar',
    'text_igm_tr_master_off': 'Master de cheats OFF',
    'text_igm_tr_saved': 'Cheat salvo',
    'text_igm_tr_savefail': 'Falha ao salvar o cheat',
    'text_igm_tr_unpin': 'REMOVER DA LISTA',
    'mtext_mm_cfg': 'Configurações',
    'mtext_mm_sysinfo': 'Informações do Sistema',
    'mtext_cfg_time': 'Ajustar Relógio',
    'mtext_cfg_ask_clock': 'Pedir relógio ao iniciar',
    'mtext_cfg_bsx': 'Opções BS-X',
    'mtext_cfg_browser': 'Opções do Navegador',
    'mtext_cfg_chip': 'Opções de Chip',
    'mtext_cfg_sgb': 'Opções SGB',
    'mtext_cfg_ingame': 'Opções no Jogo',
    'mtext_cfg_savestates': 'Opções de Savestates',
    'mtext_cfg_scic': 'Opções SuperCIC',
    'mtext_cfg_patch': 'Opções de Patches',
    'mtext_bsx_timesource': 'Relógio BS-X',
    'mtext_bsx_time': 'Hora customizada',
    'mtext_scic_enable': 'Ativar SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Modo vídeo do menu',
    'mtext_scic_vmode_game': ' {129}Modo vídeo do jogo',
    'mtext_scic_buscompat': 'Compat. de barramento',
    'mtext_browser_sort': 'Ordenar diretórios',
    'mtext_browser_hide_ext': 'Ocultar extensões',
    'mtext_browser_msu_folders': 'Abrir pastas MSU-1 como jogo',
    'mtext_browser_sd2snes_dir': 'Mostrar pasta sd2snes',
    'mtext_browser_screensaver': 'Protetor de tela',
    'mtext_browser_screensaver_timeout': 'Escurecer tela após',
    'mtext_browser_ledbright': 'Brilho dos LEDs',
    'mtext_ingame_cheats': 'Iniciar com cheats',
    'mtext_ingame_shortreset': 'Reset para o menu',
    'mtext_ingame_enable': 'Hook no jogo',
    'mtext_ingame_buttons': ' {129}Botões no jogo',
    'mtext_ingame_cheat_overlay': ' {129}Menu dentro do jogo',
    'mtext_ingame_game_manual': ' {129}Manual do jogo',
    'mtext_ingame_holdoff': ' {129}Espera inicial',
    'mtext_ingame_savestate': 'Savestates no jogo',
    'mtext_savestate_slots': ' {129}Slots de savestate',
    'mtext_loadstate_delay': ' {129}Atraso ao carregar',
    'mtext_sgb_enable_hooks': 'Hooks no jogo',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'Recursos do SGB',
    'mtext_sgb_spr_increase': 'Limite máx. sprites (40)',
    'mtext_sgb_volume_boost': 'Boost de volume',
    'mtext_sgb_clock': 'Clock (Timing)',
    'mtext_sgb_bios': 'Versão do BIOS',
    'mtext_ingame_regionpatch': 'Patch auto. de região',
    'mtext_ingame_1chiptransientfixes': 'Correções 1CHIP',
    'mtext_ingame_brightlimit': 'Limite de brilho',
    'mtext_ingame_resetpatch': 'Patch de reset (clock)',
    'mtext_ingame_autosave': 'Auto-salvar',
    'mtext_ingame_autosave_msu1': ' {129}Auto-salvar MSU-1',
    'mtext_chip_cx4_speed': 'Velocidade Cx4',
    'mtext_chip_cc_time_limit': "Timer do Competition Cart (min)",
    'mtext_chip_gsu_speed': 'Velocidade SuperFX',
    'mtext_chip_msu1_volume_boost': 'Boost volume MSU-1',
    'mtext_a26_width': 'Largura de vídeo Atari 2600',
    'mdesc_mm_last': 'Mostra até 10 jogos recentes',
    'mdesc_mm_favorites': 'Mostra até 20 jogos favoritos',
    'mdesc_mm_cfg': 'Configurar o sd2snes',
    'mdesc_mm_sysinfo': 'Info de FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Ajustar data e hora',
    'mdesc_cfg_ask_clock': 'Pede a hora ao iniciar enquanto o relógio não for ajustado',
    'mdesc_cfg_bsx': 'Opções específicas BS-X/Satellaview',
    'mdesc_cfg_browser': 'Alterar opções do navegador',
    'mdesc_cfg_chip': 'Recursos especiais de chip',
    'mdesc_cfg_ingame': 'Recursos durante o jogo',
    'mdesc_cfg_sgb': 'Recursos do Super Game Boy',
    'mdesc_cfg_savestates': 'Recursos de savestates',
    'mdesc_cfg_scic': 'Ativar SuperCIC e modos de vídeo',
    'mdesc_cfg_patch': 'Opções de aplicação de patches IPS/BPS',
    'mdesc_bsx_timesource': 'Data/hora vistas pelos jogos BS-X',
    'mdesc_bsx_time': 'Hora e data customizadas para BS-X',
    'mdesc_scic_enable': 'Necessário para recursos SuperCIC',
    'mdesc_scic_vmode_menu': 'Modo de vídeo do menu',
    'mdesc_scic_vmode_game': 'Modo de vídeo dos jogos',
    'mdesc_scic_buscompat': 'Timing de barramento estreito para consoles onde alguns jogos travam ou dão glitch. Ative só se você vê travamentos neste console.',
    'mdesc_browser_sort': 'Ordenar listas de arquivos',
    'mdesc_browser_hide_ext': 'Ocultar extensões de arquivos',
    'mdesc_browser_msu_folders': 'A numa pasta com uma só ROM MSU-1 abre o jogo',
    'mdesc_browser_sd2snes_dir': 'Mostra /sd2snes na lista de arquivos',
    'mdesc_browser_screensaver': 'Escurecer a tela após um tempo',
    'mdesc_browser_screensaver_timeout': 'Tempo para escurecer a tela',
    'mdesc_browser_ledbright': 'Alterar brilho dos LEDs',
    'mdesc_ingame_cheats': 'Iniciar com cheats ativados',
    'mdesc_ingame_shortreset': 'Para onde o reset leva. Pasta/ROM reabrem a pasta do último jogo. Duração: toque curto reseta o jogo, longo leva à ROM.',
    'mdesc_ingame_enable': 'Necessário para botões e cheats 7E/7F',
    'mdesc_ingame_buttons': 'Botões no jogo (reset, cheats{127}{128}). Requer hook ativo.',
    'mdesc_ingame_cheat_overlay': 'Menu dentro do jogo (segure L+R+Y+Esq): cheats, savestates, saves e guias. Requer hook. Indisponível em alguns chips especiais.',
    'mdesc_ingame_game_manual': 'Mostra o manual do jogo no menu no jogo. Requer <rom>.man em /sd2snes/info.',
    'mdesc_ingame_holdoff': 'Espera 10s antes de ativar o hook',
    'mdesc_ingame_savestate': 'Savestates no jogo. Padrão: Salvar Start+R, Carregar Start+L',
    'mdesc_savestate_slots': 'Slots de savestate. Select+Dpad escolhe o slot',
    'mdesc_loadstate_delay': 'Ajustar atraso ao carregar savestate (frames)',
    'mdesc_sgb_enable_hooks': 'Necessário para botões no jogo',
    'mdesc_sgb_enable_state': 'Savestates internos no SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Ativar/desativar recursos SGB',
    'mdesc_sgb_spr_increase': 'Aumentar número de sprites visíveis',
    'mdesc_sgb_volume_boost': 'Aumentar volume do áudio SGB',
    'mdesc_sgb_clock': 'Ajustar clock do SGB (timing)',
    'mdesc_sgb_bios': 'Selecionar versão de BIOS do SGB',
    'mdesc_ingame_regionpatch': 'Ignora proteção simples de região',
    'mdesc_ingame_1chiptransientfixes': 'Corrige glitches de brilho em 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limitar brilho geral (RGB em 1CHIP)',
    'mdesc_ingame_resetpatch': 'Patch de reset para alinhar clocks',
    'mdesc_ingame_autosave': 'Salvar SRM automaticamente quando muda',
    'mdesc_ingame_autosave_msu1': 'MSU-1: salva SRM em pausas. Pode travar.',
    'mdesc_chip_cx4_speed': 'Velocidade do soft core Cx4',
    'mdesc_chip_cc_time_limit': "Timer de round dos cartuchos de evento (Campus Challenge '92, PowerFest '94)",
    'mdesc_chip_gsu_speed': 'Velocidade do soft core SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Boost de volume MSU-1 (Rev. E-G)',
    'mdesc_a26_width': 'Largura da imagem do Atari 2600: 160 é nativa 1:1, 256 preenche a tela',
    'mdesc_cx4_speed_fast': 'Rodar o mais rápido possível',
    'mdesc_cx4_speed_normal': 'Rodar aprox. na velocidade original',
    'mdesc_gsu_speed_fast': 'Rodar o mais rápido possível',
    'mdesc_gsu_speed_normal': 'Rodar aprox. na velocidade original',
    'text_filesel_selected_file': 'Arquivo selecionado',
    'text_filesel_context_add_to_favorites': 'Adicionar aos favoritos',
    'mdesc_filesel_context_add_to_favorites': 'Adiciona o arquivo aos favoritos',
    'text_filesel_context_remove_from_favorites': 'Remover dos favoritos',
    'mdesc_filesel_context_remove_from_favorites': 'Remove o arquivo dos favoritos',
    'text_recent_context_remove_from_recent': 'Remover dos recentes',
    'mdesc_recent_context_remove_from_recent': 'Remove o arquivo dos jogos recentes',
    'text_filesel_set_as_autoboot': 'Definir como autoboot',
    'mdesc_filesel_set_as_autoboot': 'Inicia esta ROM no próximo power-on (START cancela)',
    'text_filesel_set_as_bgm': 'Definir como música do menu',
    'mdesc_filesel_set_as_bgm': 'Usar este SPC como música de fundo do menu',
    'text_filesel_context_delete_file': 'Deletar',
    'mdesc_filesel_context_delete_file': 'Deleta o arquivo selecionado',
    'text_filesel_context_delete_srm': 'Deletar save',
    'mdesc_filesel_context_delete_srm': 'Deleta o arquivo de save SRM para esta ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Visualizar, ativar ou desativar cheats do arquivo YAML desta ROM',
    'text_filesel_context_gameinfo': 'Ficha do jogo',
    'mdesc_filesel_context_gameinfo': 'Mostra a ficha deste jogo (capa, screenshot e dados) antes de jogar',
    'text_cheat_yes': 'Sim',
    'text_cheat_no': 'Não',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Nome',
    'text_cheat_none_msg': 'Nenhum cheat para esta ROM',
    'text_confirm_delete_file': 'Deletar este arquivo?',
    'text_confirm_delete_srm': 'Deletar o arquivo de save?',
    'text_confirm_hint': 'A:Confirmar  B:Cancelar',
    'text_confirm_no_sel': '[Não]',
    'text_confirm_no_unsel': ' Não ',
    'text_confirm_yes_sel': '[Sim]',
    'text_confirm_yes_unsel': ' Sim ',
    'text_statusbar_play': 'A:Jogar B:Voltar X:Menu',
    'text_statusbar_keys': 'A:OK B:Voltar X:Menu Y:Contexto',
    'text_statusbar_spc': 'B:Voltar',
    'text_statusbar_menu': 'A:OK B:Voltar',
    'text_last': 'Jogos recentes',
    'text_favorite': 'Jogos favoritos',
    'text_no_last': 'Nenhum recente',
    'text_no_favorite': 'Nenhum favorito',
    'text_favorites_full': 'Favoritos cheio',
    'text_err_supplfile': 'Arquivo ausente:',
    'text_err_noimpl': 'Chip não suportado:',
    'text_err_nohw': 'Requer hardware Mk.III:',
    'text_err_generic': 'Erro ao carregar:',
    'text_on_p1': 'Lig: P1',
    'text_on_p2': 'Lig: P2',
    'text_on': 'Lig',
    'text_off': 'Des',
    'text_15_max': '15 (máx)',
    'text_theme': 'Tema',
    'text_cover_large': 'Grande',
    'text_cover_small': 'Pequeno',
    'text_gameinfo_context': 'Contexto',
    'text_nav_folder': 'Pasta',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Duração',
    'text_enabled': 'Ativado',
    'text_disabled': 'Desativ.',
    'text_normal': 'Normal',
    'text_fast': 'Rápido',
    'text_a26_w256': '256 (esticado)',
    'text_rtc': 'Tempo real',
    'text_custom': 'Custom.',
    'text_yes': 'Sim',
    'text_no': 'Não',
    'text_auto': 'Auto',
    'text_add': 'Adicionar',
    'text_remove': 'Remover',
    'text_edit': 'Editar',
    'text_save': 'Salvar',
    'text_1min': '1 min',
    'text_2min': '2 mins',
    'text_3min': '3 mins',
    'text_4min': '4 mins',
    'text_5min': '5 mins',
    'text_10min': '10 mins',
    'text_15min': '15 mins',
    'text_20min': '20 mins',
    'text_30min': '30 mins',
    'text_45min': '45 mins',
    'text_60min': '1 hora',
    'text_spcplay': 'Tocador de SPC',
    'text_spcload': 'Carregando SPC no SPC700{127}{128}  ',
    'text_spcstarta': '**** Tocando SPC ****',
    'text_spcstartb': 'Nome:  ',
    'text_spcstartc': 'Música:',
    'text_spcstartd': 'Artista:',
    'text_spc_statusbar': 'B:Voltar',
    'text_loading': 'Carregando{127}{128}                     ',
    'text_saving': 'Salvando{127}{128}                       ',
    'text_cheat': 'Cheats para ',
    'text_cheat_noname': '(sem nome)',
    'text_igm_cheat_noname': '(sem nome)',
    'text_igm_ch_none': 'Nenhum cheat',
    'text_igm_ft_tab': '<>:ABA L/R:PONTAS A:ABRIR B:FECHAR',
    'text_igm_ft_cheats': 'A:LIG/DES Y:EDITAR SEL:NOVO X:CHEATS B:VOLTAR',
    'text_igm_ft_generic': 'A:SELECIONAR B:VOLTAR',
    'text_igm_master_on': 'CHEATS: LIG',
    'text_igm_master_off': 'CHEATS: DES',
    'text_igm_ft_ce_edit': 'A:EDITAR SEL:+CODIGO Y:REMOVER B:VOLTAR',
    'text_igm_ft_ce_kbd': 'A:DIGITAR Y:APAGAR SEL:ESPACO X:OK B:CANCELAR',
    'text_igm_ce_title_new': 'NOVO CHEAT',
    'text_igm_ce_title_edit': 'EDITAR CHEAT',
    'text_igm_ce_name': 'Nome:',
    'text_igm_ce_save': 'SALVAR',
    'text_igm_ce_delete': 'EXCLUIR CHEAT',
    'text_igm_ce_confirm': 'Excluir este cheat?',
    'text_igm_ce_confirm_keys': 'A: sim   B: não',
    'text_igm_ce_nosup': 'Atualize o firmware',
    'text_igm_ce_full': 'A lista de cheats está cheia',
    'text_igm_ce_badcode': 'Código inválido',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Versão firmware: {2}',
    'text_si_busy': 'Calculando espaço em disco{127}{128}',
    'text_si_removed': '    *** SD removido/USB ocupado ***',
    'text_si_maker': 'Fabricante SD:   0x{3}, {34}{4}{34}',
    'text_si_product': 'Nome do produto: {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'Serial SD:       {8}, Fab. {9}/{10}',
    'text_si_acc': 'Acesso SD:    {11}.{12} / {13}.{14} ms med/max',
    'text_si_accmeas': 'Acesso SD:    medindo{127}{128}',
    'text_si_usage': 'Uso do SD:  {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'lendo{127}{128}',
    'text_si_sgb_missing': 'ausente',
    'text_si_sgb_mismatch': 'errado',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'Modo CIC: {19}',
    'text_si_clk': 'Clock SNES: {20}Hz',
    'text_si_clkmeas': 'Clock SNES: medindo{127}{128}',
    'text_si_u16on': 'Ultra16 série {21} (Autoboot Lig)',
    'text_si_u16off': 'Ultra16 série {21} (Autoboot Des)',
    'text_si_model': 'Modelo: {22}',
    'text_si_updatefw': '*** Atualize a firmware ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Teste de memória',
    'mdesc_mm_memtest': 'Verifica a fiação FPGA-RAM (10 s). O teste completo verifica cada célula (30 s). Reinicia o console.',
    'text_mtl_prompt': 'A: Testar linhas  X: Completo  B: Sair',
    'text_mtl_prompt2': 'Ambos reiniciam o console. X leva 30s.',
    'text_mtl_run': 'Testando a memória, aguarde{127}{128}',
    'text_mtl_none': 'Nenhum teste executado ainda.',
    'text_mtl_pass': 'Todas as linhas da RAM OK.',
    'text_mtl_fail': 'Falhas encontradas:',
    'text_mtl_nocore': '/sd2snes/fpga_test ausente/inválido.',
    'text_mtl_more': '(mais falhas não mostradas)',
    'text_mtl_cellpass': 'Todas as células verificadas.',
    'text_mtl_cellfail': 'Primeira célula ruim em 0x',
    'text_mtl_cellskip': 'Varredura pulada: corrija as linhas.',
    'text_mt_data': 'ver linha de dados D',
    'text_mt_addr': 'ver linha de endereço A',
    'text_mt_short': 'possível curto A',
    'text_mt_bytesel': 'ver LB# / UB#',
    'text_mt_ctrl': 'ver CE# / OE# / WE#',
    'text_mt_fpgactrl': 'ver CE# / OE# / WE# do FPGA',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'Tocador de PCM',
    'text_pcm_prompt': 'A: Tocar/Pausar   B: Fechar',
    'text_pcm_promptb': 'B: Fechar',
    'text_pcm_paused': 'Pausado',
    'text_pcm_erropen': 'Não foi possível ler o arquivo.',
    'text_pcm_errmagic': 'Não é um arquivo PCM MSU-1.',
    'text_pcm_nosup': '*** Atualize o firmware ***',
    'text_st_slotb_title': 'Sufami Turbo - Slot B',
    'text_st_slotb_footer': 'A:Jogar  B:Voltar  <>:Pag  LR:Ini/Fim',
    'text_st_slotb_none': '[Sem cartucho no Slot B]',
    'text_ips_nopatch': '[Sem patch]',
    'text_ips_header': 'Patches',
    'mtext_patch_verify': 'Verificar Integridade (aprox. 23s)',
    'mtext_patch_clearppu': 'Limpar PPU no boot',
    'mdesc_patch_verify': 'Relê a ROM aplicada para verificar (carrega bem mais lentamente)',
    'mdesc_patch_clearppu': 'Zera VRAM/CGRAM/OAM antes de bootar ROM com patch (romhacks que pulam o init da PPU)',
    'text_patch_hdr_auto': 'autom.',
    'text_patch_hdr_on': 'cabeç.',
    'text_patch_hdr_off': 'cru   ',
    'text_patch_footer': 'A:Jogar  Y:Mais  B:Voltar  <>:Pag  LR:Ini/Fim',
    'text_patch_creating': 'Criando ROM com patch...',
    'text_err_patchexport': 'Falha ao gravar a ROM',
    'text_patch_export_ok': 'ROM com patch criada',
    'text_patch_export_part': 'ROM ok, assets incompletos',
    'text_patch_export_exists': 'ROM com patch já existe',
    'text_patch_hdrsel_auto': 'Auto (detectar)',
    'text_patch_hdrsel_on': 'Com cabeçalho',
    'text_patch_hdrsel_off': 'Sem cabeçalho',
    'mtext_patch_header_mode': 'Modo de cabeçalho',
    'mdesc_patch_header_mode': 'Como os offsets do IPS sao lidos: Auto, Cabeçalho (desloca 512 B) ou Cru.',
    'mtext_patch_create_rom': 'Criar ROM com patch',
    'mdesc_patch_create_rom': 'Grava a ROM com o patch aplicado ao lado da original, copiando capa, saves, cheats e guias. Pode levar vários minutos.',
    'cheat_tab_head': 'Nome                                     Ativado',
    'cheat_tab_hint_text': ' A:On/Off Y:Editar Sel:Novo B:Sair',
    'mtext_browser_showcov': 'Mostrar capas',
    'mdesc_browser_showcov': 'Exibir capas dos jogos no menu',
    'mtext_browser_covlists': ' {129}Favoritos/Recentes',
    'mdesc_browser_covlists': 'Exibir capas também nas listas Recentes e Favoritos',
    'mtext_browser_menumusic': 'Música do menu',
    'mtext_browser_menumusic_random': ' {129}Música aleatória',
    'mtext_browser_menusfx': 'Sons do menu',
    'mtext_browser_text_outline': 'Contorno do texto',
    'mtext_browser_text_aa': 'Suavização do texto',
    'mdesc_browser_menumusic': 'Tocar música de fundo (menu.spc) no menu',
    'mtext_browser_sortfav': 'Ordenar favoritos',
    'mdesc_browser_sortfav': 'Ordena a lista de favoritos em ordem alfabética',
    'mtext_browser_restoretheme': 'Restaurar tema',
    'mdesc_browser_restoretheme': 'Voltar o tema do menu para o padrão de fábrica',
    'mtext_browser_restoreclassic': 'Restaurar tema clássico',
    'mdesc_browser_restoreclassic': 'Carregar o visual clássico do sd2snes (precisa de /sd2snes/classic.thm no cartão)',
    'mtext_browser_restoremusic': 'Restaurar música',
    'mdesc_browser_restoremusic': 'Voltar a música do menu para o padrão (menu.spc)',
    'mdesc_browser_menumusic_random': 'Sorteia um .spc da pasta de músicas a cada carga',
    'mdesc_browser_text_outline': 'Contorno escuro no texto do menu: seguir o tema, ou forçar',
    'mdesc_browser_text_aa': 'Bordas suaves no texto do menu: seguir o tema, ou forçar',
    'text_mm_language': 'Idioma',
    'mdesc_mm_language': 'Define o idioma do menu/firmware',
    'mdesc_browser_menusfx': 'Tocar efeitos sonoros ao navegar pelo menu',
    'mtext_browser_gameinfo': 'Ficha de Jogo',
    'mtext_gameinfo_enable': 'Mostrar tela de info',
    'mdesc_browser_gameinfo': 'Mostra capa, screenshot e infos antes de iniciar uma ROM que tenha uma entrada em /sd2snes/info',
    'mdesc_cfg_gameinfo': 'Opções da tela de info do jogo (antes de bootar)',
    'mtext_browser_gameinfo_video': ' {129}Exibir vídeo',
    'mdesc_browser_gameinfo_video': 'Reproduz o clipe animado na Ficha de Jogo (desligado mostra um snapshot estático)',
    'mtext_browser_gameinfo_music': ' {129}Tocar música do vídeo',
    'mdesc_browser_gameinfo_music': 'Toca a trilha do vídeo enquanto o clipe aparece. Requer Exibir vídeo.',
    'text_gi_developer': 'Produtora',
    'text_gi_publisher': 'Distribuidora',
    'text_gi_year': 'Ano',
    'text_gi_players': 'Jogadores',
    'text_gi_genre': 'Gênero',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Jogar  B: Voltar  Y: Descrição',
    'text_gi_footer_nav': 'A:Jogar B:Voltar Y:Desc Cima/Baixo:Jogo',
    'text_gi_footer_full': 'B: Voltar  Cima/Baixo: Rolar',
    'text_gi_footer_man': 'A: Jogar  B: Voltar  Y: Descrição  X: Guias',
    'text_gi_footer_nav_man': 'A:Jogar B:Voltar Y:Desc X:Guias Cima/Baixo:Jogo',
    'text_gi_footer_pick': 'A: Abrir  B: Voltar',
    'text_gi_slug_manual': 'Manual',
    'text_gi_slug_guide': 'Guia',
    'text_gi_slug_map': 'Mapa',
    'text_gi_slug_insert': 'Encarte',
    'text_gi_slug_other': 'Outro',
}
