"""Italian (Italiano) strings for the sd2snes menu.

Maps const.a65 string labels -> it text. Accented chars are written as real
UTF-8 here; build_const.py encodes them to the font byte codes (the Italian
graves ì ò È Ì Ò Ù live at 230-235, see fontedit.py additalian).
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions ARE rendered now (the selected option's help box) and
localized like the rest; the pool lives in bank $C1 (see build_const.py).
"""

TRANSLATIONS = {
    'text_clkset': "Imposta l'ora",
    'text_mainmenu': 'Menu Principale',
    'text_mm_file': 'Esplora File',
    'text_mm_last': 'Giochi Recenti',
    'text_mm_favorites': 'Giochi Preferiti',
    # In-game TAB menu HELP tab (Phase 2)
    'text_igm_hdr_controls': 'COMANDI IN GIOCO',
    'text_igm_open': 'Apri menu:         L+R+Y+Sin',
    'text_igm_save': 'Salva savestate:   Start+R',
    'text_igm_load': 'Carica savestate:  Start+L',
    'text_igm_slot': 'Scegli slot:       Select + D-Pad',
    'text_igm_reset': 'Reset al menu:     L+R+Select+X',
    'text_igm_hdr_keys': 'TASTI DEL MENU',
    'text_igm_tab': 'L / R:     cambia scheda',
    'text_igm_page': 'Sin/Des:   cambia pagina',
    'text_igm_nav': 'Su / Giù:  muovi',
    'text_igm_act': 'A: applica   X: tutti',
    'text_igm_close': 'B: chiudi menu',
    'text_igm_note': 'Alcune combo si impostano in Opzioni',
    'text_igm_st_title': 'SCEGLI SLOT SAVESTATE',
    'text_igm_st_slot': 'SLOT',
    'text_igm_st_full': 'OCCUPATO',
    'text_igm_st_empty': 'VUOTO',
    'text_igm_st_hint': 'Start+R salva  Start+L carica',
    'text_igm_st_disabled': 'Slot savestate disattivati',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'AIUTO',
    'text_igm_tab_manual': 'GUIDE',
    'text_igm_tab_trainer': 'TRAINER',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    'text_igm_sv_title': 'SALVATAGGIO',
    'text_igm_sv_nosram': 'Questo gioco non ha salvataggio a batteria',
    'text_igm_sv_file': 'File .srm:',
    'text_igm_sv_exists': 'PRESENTE',
    'text_igm_sv_missing': 'ASSENTE',
    'text_igm_sv_size': 'Dimensione:',
    'text_igm_sv_write': 'Ultima scr.:',
    'text_igm_sv_autosave': 'Autosalva:',
    'text_igm_sv_on': 'ATTIVO',
    'text_igm_sv_off': 'DISATTIVO',
    'text_igm_sv_hint_on': 'Il salvataggio viene scritto durante il gioco',
    'text_igm_sv_hint_off': 'Autosalva off - salva dal menu del gioco',
    'text_igm_sv_slottitle': 'SCEGLI SLOT SRAM',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Attivo al prossimo avvio del gioco',
    'text_igm_mn_title': 'MANUALE DEL GIOCO',
    'text_igm_mn_read': 'A: Leggi il manuale',
    'text_igm_mn_pages': 'pagine',
    'text_igm_mn_notfound': 'Manuale non trovato',
    'text_igm_mn_error': 'Errore caricando il manuale',
    'text_igm_mn_guide': 'GUIDA',
    'text_igm_mn_select': 'SCEGLI UNA GUIDA',
    'text_igm_mn_keys1': 'A: zoom 2x   L/R: cambia pagina',
    'text_igm_mn_keys2': 'D-Pad: muovi   B: indietro',
    'text_igm_mn_slug_manual': 'Manuale',
    'text_igm_mn_slug_guide': 'Guida',
    'text_igm_mn_slug_map': 'Mappa',
    'text_igm_mn_slug_insert': 'Inserto',
    'text_igm_mn_slug_other': 'Altro',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'TRAINER RAM',
    'text_igm_tr_searchtype': 'Tipo ricerca:',
    'text_igm_tr_datatype': 'Dimensione:',
    'text_igm_tr_value': 'Valore:',
    'text_igm_tr_candidates': 'Candidati:',
    'text_igm_tr_compare': 'Confronta:',
    'text_igm_tr_exact': 'Valore esatto',
    'text_igm_tr_unknown': 'Sconosciuto',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Uguale a',
    'text_igm_tr_ne': 'Diverso',
    'text_igm_tr_changed': 'Cambiato',
    'text_igm_tr_unchanged': 'Invariato',
    'text_igm_tr_increased': 'Aumentato',
    'text_igm_tr_decreased': 'Diminuito',
    'text_igm_tr_gt': 'Maggiore di',
    'text_igm_tr_lt': 'Minore di',
    'text_igm_tr_newsearch': 'NUOVA RICERCA',
    'text_igm_tr_filter': 'FILTRA',
    'text_igm_tr_results': 'RISULTATI',
    'text_igm_tr_reset': 'AZZERA RICERCA',
    'text_igm_tr_address': 'INDIRIZZO',
    'text_igm_tr_current': 'ATTUALE',
    'text_igm_tr_setvalue': 'SCRIVI VALORE',
    'text_igm_tr_freeze': 'CONGELA',
    'text_igm_tr_unfreeze': 'SCONGELA',
    'text_igm_tr_savecheat': 'SALVA CHEAT',
    'text_igm_tr_frozen': 'CONGELATO',
    'text_igm_tr_searching': 'Ricerca...',
    'text_igm_tr_noresults': 'Nessun risultato',
    'text_igm_tr_toomany': 'Troppi risultati - filtra ancora',
    'text_igm_tr_dropped_rst': 'Ricerca azzerata - console reset',
    'text_igm_tr_nofreeze': 'Massimo 4 congelati',
    'text_igm_tr_hint_setup': 'A: scegli   D-Pad: cambia',
    'text_igm_tr_hint_edit': 'D-Pad: modifica   A: OK   B: esci',
    'text_igm_tr_hint_list': 'A: ispeziona   B: indietro',
    'text_igm_tr_master_off': 'Master cheat OFF',
    'text_igm_tr_saved': 'Cheat salvato',
    'text_igm_tr_savefail': 'Cheat non salvato',
    'text_igm_tr_unpin': 'RIMUOVI DALLA LISTA',
    'mtext_mm_cfg': 'Configurazione',
    'mtext_mm_sysinfo': 'Informazioni di Sistema',
    'mtext_cfg_time': 'Imposta Orologio',
    'mtext_cfg_ask_clock': "Chiedere l'ora all'avvio",
    'mtext_cfg_bsx': 'Opzioni BS-X',
    'mtext_cfg_browser': 'Opzioni Browser',
    'mtext_cfg_chip': 'Opzioni Chip',
    'mtext_cfg_sgb': 'Opzioni SGB',
    'mtext_cfg_ingame': 'Opzioni In Gioco',
    'mtext_cfg_savestates': 'Opzioni Savestate',
    'mtext_cfg_scic': 'Opzioni SuperCIC',
    'mtext_cfg_patch': 'Opzioni Patch',
    'mtext_bsx_timesource': 'Orologio BS-X',
    'mtext_bsx_time': 'Ora personalizzata',
    'mtext_scic_enable': 'Attiva SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Modo video menu',
    'mtext_scic_vmode_game': ' {129}Modo video gioco',
    'mtext_scic_buscompat': 'Compat. timing bus',
    'mtext_browser_sort': 'Ordina cartelle',
    'mtext_browser_hide_ext': 'Nascondi estensioni',
    'mtext_browser_msu_folders': 'Apri cartelle MSU-1 come gioco',
    'mtext_browser_sd2snes_dir': 'Mostra cartella sd2snes',
    'mtext_browser_screensaver': 'Salvaschermo',
    'mtext_browser_screensaver_timeout': 'Oscura schermo dopo',
    'mtext_browser_ledbright': 'Luminosità LED',
    'mtext_ingame_cheats': 'Avvia con i cheat attivi',
    'mtext_ingame_shortreset': 'Reset al menu',
    'mtext_ingame_enable': 'Hook in gioco',
    'mtext_ingame_buttons': ' {129}Tasti in gioco',
    'mtext_ingame_cheat_overlay': ' {129}Menu in gioco',
    'mtext_ingame_game_manual': ' {129}Manuale del gioco',
    'mtext_ingame_holdoff': ' {129}Attesa iniziale',
    'mtext_ingame_savestate': 'Savestate in gioco',
    'mtext_savestate_slots': ' {129}Slot savestate',
    'mtext_loadstate_delay': ' {129}Ritardo carica (frame)',
    'mtext_sgb_enable_hooks': 'Hook in gioco',
    'mtext_sgb_enable_state': 'Savestate (XR, XL)',
    'mtext_sgb_enh_override': 'Funzioni SGB',
    'mtext_sgb_spr_increase': 'Limite massimo sprite (40)',
    'mtext_sgb_volume_boost': 'Aumento volume',
    'mtext_sgb_clock': 'Clock (Timing)',
    'mtext_sgb_bios': 'Versione BIOS',
    'mtext_ingame_regionpatch': 'Patch regione auto.',
    'mtext_ingame_1chiptransientfixes': 'Correzioni 1CHIP',
    'mtext_ingame_brightlimit': 'Limite luminosità',
    'mtext_ingame_resetpatch': 'Patch reset (fase clock)',
    'mtext_ingame_autosave': 'Autosalvataggio',
    'mtext_ingame_autosave_msu1': ' {129}Autosalva MSU-1',
    'mtext_chip_cx4_speed': 'Velocità Cx4',
    'mtext_chip_cc_time_limit': "Timer del Competition Cart (min)",
    'mtext_chip_gsu_speed': 'Velocità SuperFX',
    'mtext_chip_msu1_volume_boost': 'Aumento volume MSU-1',
    'mtext_a26_width': 'Larghezza video Atari 2600',
    'mdesc_mm_last': 'Mostra fino a 10 giochi recenti',
    'mdesc_mm_favorites': 'Mostra fino a 20 giochi preferiti',
    'mdesc_mm_cfg': 'Configura il sd2snes',
    'mdesc_mm_sysinfo': 'Info su versione FW, scheda SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Imposta data e ora',
    'mdesc_cfg_ask_clock': "Chiede l'ora all'avvio finché l'orologio non è impostato",
    'mdesc_cfg_bsx': 'Opzioni specifiche BS-X/Satellaview',
    'mdesc_cfg_browser': 'Cambia le opzioni del browser file',
    'mdesc_cfg_chip': 'Imposta le funzioni dei chip speciali',
    'mdesc_cfg_ingame': 'Imposta le funzioni in gioco',
    'mdesc_cfg_sgb': 'Imposta le funzioni Super Game Boy',
    'mdesc_cfg_savestates': 'Imposta le funzioni dei savestate',
    'mdesc_cfg_scic': 'Attiva/disattiva SuperCIC e imposta i modi video',
    'mdesc_cfg_patch': 'Opzioni per il soft-patching IPS/BPS',
    'mdesc_bsx_timesource': 'Scegli quale data e ora vedono i giochi BS-X',
    'mdesc_bsx_time': 'Imposta data e ora personalizzate per i giochi BS-X',
    'mdesc_scic_enable': 'Necessario per le funzioni SuperCIC',
    'mdesc_scic_vmode_menu': 'Imposta il modo video del menu',
    'mdesc_scic_vmode_game': 'Imposta il modo video dei giochi',
    'mdesc_scic_buscompat': 'Timing del bus cartuccia più stretto per console dove alcuni giochi si bloccano o hanno glitch. Attiva solo se vedi blocchi su questa console.',
    'mdesc_browser_sort': 'Scegli se ordinare le liste di file',
    'mdesc_browser_hide_ext': 'Scegli se nascondere le estensioni dei file',
    'mdesc_browser_msu_folders': 'A su una cartella con una sola ROM MSU-1 apre il gioco',
    'mdesc_browser_sd2snes_dir': 'Mostra /sd2snes nella lista file',
    'mdesc_browser_screensaver': "Oscura lo schermo dopo un po' di tempo",
    'mdesc_browser_screensaver_timeout': 'Imposta dopo quanto tempo oscurare lo schermo',
    'mdesc_browser_ledbright': 'Cambia la luminosità dei LED',
    'mdesc_ingame_cheats': 'Avvia con i cheat già attivi. Si può cambiare con i tasti in gioco',
    'mdesc_ingame_shortreset': "Dove porta il reset. Cartella/ROM riaprono la cartella dell'ultimo gioco. Durata: pressione breve resetta il gioco, lunga va alla ROM.",
    'mdesc_ingame_enable': 'Necessario per i tasti in gioco e i cheat 7E/7F',
    'mdesc_ingame_buttons': "Attiva i tasti in gioco (reset, attiva/disattiva cheat{127}{128}). Richiede l'hook in gioco attivo.",
    'mdesc_ingame_cheat_overlay': "Menu in gioco (tieni L+R+Y+Sin): cheat, savestate, salvataggi e guide. Richiede l'hook. Non disponibile su alcuni giochi con chip speciali.",
    'mdesc_ingame_game_manual': 'Mostra il manuale del gioco nel menu in gioco. Richiede <rom>.man in /sd2snes/info.',
    'mdesc_ingame_holdoff': "Attende 10 secondi prima di attivare l'hook (aiuta alcuni giochi ad avviarsi con l'hook attivo)",
    'mdesc_ingame_savestate': 'Attiva i savestate in gioco e scegli il controller. Predef.: Salva - Start+R / Carica - Start+L',
    'mdesc_savestate_slots': 'Attiva gli slot savestate. Select+D-Pad: ogni direzione è uno slot da scegliere',
    'mdesc_loadstate_delay': 'Regola il ritardo di caricamento dei savestate (frame)',
    'mdesc_sgb_enable_hooks': 'Necessario per i tasti in gioco',
    'mdesc_sgb_enable_state': 'Attiva i savestate integrati su SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Disattiva/attiva le migliorie SGB',
    'mdesc_sgb_spr_increase': 'Aumenta il numero di sprite visibili supportati',
    'mdesc_sgb_volume_boost': "Aumenta il volume dell'audio SGB se è troppo basso",
    'mdesc_sgb_clock': 'Regola il clock del SGB (timing)',
    'mdesc_sgb_bios': 'Seleziona una versione del firmware/BIOS SGB',
    'mdesc_ingame_regionpatch': 'Aggira la protezione di regione semplice dei giochi',
    'mdesc_ingame_1chiptransientfixes': 'Corregge glitch di sync, scanline in dissolvenza e ombre mancanti su console 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limita la luminosità generale (es. su console 1CHIP per rispettare i livelli RGB)',
    'mdesc_ingame_resetpatch': 'Attiva la patch di reset per allineare i clock. Corregge problemi grafici in alcuni giochi',
    'mdesc_ingame_autosave': 'Salva automaticamente il file SRM quando la Save RAM cambia',
    'mdesc_ingame_autosave_msu1': "MSU-1: sfrutta alcune occasioni per autosalvare l'SRM. Può causare brevi scatti.",
    'mdesc_chip_cx4_speed': 'Imposta la velocità del soft core Cx4',
    'mdesc_chip_cc_time_limit': "Timer del round delle cartucce evento (Campus Challenge '92, PowerFest '94)",
    'mdesc_chip_gsu_speed': 'Imposta la velocità del soft core SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Aumenta il volume MSU-1 se il tuo sd2snes è troppo basso (Rev. E-G)',
    'mdesc_a26_width': 'Larghezza immagine Atari 2600: 160 è nativa 1:1, 256 riempie lo schermo',
    'mdesc_cx4_speed_fast': 'Esegui il più veloce possibile',
    'mdesc_cx4_speed_normal': 'Esegui a velocità circa originale',
    'mdesc_gsu_speed_fast': 'Esegui il più veloce possibile',
    'mdesc_gsu_speed_normal': 'Esegui a velocità circa originale',
    'text_filesel_selected_file': 'File selezionato',
    'text_filesel_context_add_to_favorites': 'Aggiungi ai preferiti',
    'mdesc_filesel_context_add_to_favorites': 'Aggiunge il file selezionato ai preferiti',
    'text_filesel_context_remove_from_favorites': 'Togli dai preferiti',
    'mdesc_filesel_context_remove_from_favorites': 'Toglie il file selezionato dai preferiti',
    'text_recent_context_remove_from_recent': 'Togli dai recenti',
    'mdesc_recent_context_remove_from_recent': 'Toglie il file dalla lista dei giochi recenti',
    'text_filesel_set_as_autoboot': 'Imposta come autoboot',
    'mdesc_filesel_set_as_autoboot': "Avvia questa ROM alla prossima accensione (tieni START all'avvio per annullare)",
    'text_filesel_set_as_bgm': 'Imposta come musica del menu',
    'mdesc_filesel_set_as_bgm': 'Usa questo SPC come musica di sottofondo del menu',
    'text_filesel_context_delete_file': 'Elimina',
    'mdesc_filesel_context_delete_file': 'Elimina il file selezionato',
    'text_filesel_context_delete_srm': 'Elimina salvataggio',
    'mdesc_filesel_context_delete_srm': 'Elimina il file di salvataggio SRM di questa ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Vedi, attiva o disattiva i cheat dal file YAML di questa ROM',
    'text_filesel_context_gameinfo': 'Info gioco',
    'mdesc_filesel_context_gameinfo': 'Mostra la scheda di questa ROM (copertina, screenshot e dati) prima di giocare',
    'text_cheat_yes': 'Sì',
    'text_cheat_no': 'No',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Nome',
    'text_cheat_none_msg': 'Nessun cheat per questa ROM',
    'text_confirm_delete_file': 'Eliminare questo file?',
    'text_confirm_delete_srm': 'Eliminare il salvataggio?',
    'text_confirm_hint': 'A:Conferma  B:Annulla',
    'text_confirm_no_sel': '[No]',
    'text_confirm_no_unsel': ' No ',
    'text_confirm_yes_sel': '[Sì]',
    'text_confirm_yes_unsel': ' Sì ',
    'text_statusbar_play': 'A:Gioca B:Indietro X:Menu',
    'text_statusbar_keys': 'A:OK B:Indietro X:Menu Y:Contesto',
    'text_statusbar_spc': 'B:Indietro',
    'text_statusbar_menu': 'A:OK B:Indietro',
    'text_last': 'Giochi recenti',
    'text_favorite': 'Giochi preferiti',
    'text_no_last': 'Nessun recente',
    'text_no_favorite': 'Nessun preferito',
    'text_favorites_full': 'Preferiti pieni',
    'text_err_supplfile': 'File non trovato:',
    'text_err_noimpl': 'Chip non supportato:',
    'text_err_nohw': 'Richiede hardware Mk.III:',
    'text_err_generic': 'Errore di caricamento:',
    'text_on_p1': 'Sì: P1',
    'text_on_p2': 'Sì: P2',
    'text_on': 'Sì',
    'text_off': 'No',
    'text_15_max': '15 (max)',
    'text_theme': 'Tema',
    'text_cover_large': 'Grande',
    'text_cover_small': 'Piccola',
    'text_gameinfo_context': 'Contesto',
    'text_nav_folder': 'Cartella',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Durata',
    'text_enabled': 'Attivo',
    'text_disabled': 'Inattivo',
    'text_normal': 'Normale',
    'text_fast': 'Veloce',
    'text_a26_w256': '256 (largo)',
    'text_rtc': 'Tempo reale',
    'text_custom': 'Person.',
    'text_yes': 'Sì',
    'text_no': 'No',
    'text_auto': 'Auto',
    'text_add': 'Aggiungi',
    'text_remove': 'Togli',
    'text_edit': 'Modifica',
    'text_save': 'Salva',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': "1 ora",
    'text_spcplay': 'Lettore SPC',
    'text_spcload': 'Carico i dati SPC nello SPC700{127}{128}',
    'text_spcstarta': '**** Riproduzione SPC in corso ****',
    'text_spcstartb': 'Nome:   ',
    'text_spcstartc': 'Brano:  ',
    'text_spcstartd': 'Artista:',
    'text_spc_statusbar': 'B:Indietro',
    'text_loading': 'Caricamento{127}{128}                    ',
    'text_saving': 'Salvataggio{127}{128}                    ',
    # Window title prefix for the cheat list, composed by the menu. "Cheats" is kept
    # as-is in every language on purpose; only the preposition is localized.
    'text_cheat': 'Cheats per ',
    'text_cheat_noname': '(senza nome)',
    'text_igm_cheat_noname': '(senza nome)',
    'text_igm_ch_none': 'Nessun cheat',
    'text_igm_ft_tab': '<>:SCHEDA L/R:ESTREMI A:APRI B:CHIUDI',
    'text_igm_ft_cheats': 'A:ON/OFF Y:MODIFICA SEL:NUOVO X:CHEATS B:INDIETRO',
    'text_igm_ft_generic': 'A:SCEGLI B:INDIETRO',
    'text_igm_master_on': 'CHEATS: ON',
    'text_igm_master_off': 'CHEATS: OFF',
    'text_igm_ft_ce_edit': 'A:MODIFICA SEL:+CODICE Y:RIMUOVI B:INDIETRO',
    'text_igm_ft_ce_kbd': 'A:SCRIVI Y:CANCELLA SEL:SPAZIO X:OK B:ANNULLA',
    'text_igm_ce_title_new': 'NUOVO CHEAT',
    'text_igm_ce_title_edit': 'MODIFICA CHEAT',
    'text_igm_ce_name': 'Nome:',
    'text_igm_ce_save': 'SALVA',
    'text_igm_ce_delete': 'ELIMINA CHEAT',
    'text_igm_ce_confirm': 'Eliminare questo cheat?',
    'text_igm_ce_confirm_keys': 'A: sì   B: no',
    'text_igm_ce_nosup': 'Aggiorna il firmware',
    'text_igm_ce_full': 'La lista dei cheat è piena',
    'text_igm_ce_badcode': 'Codice non valido',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Versione firmware: {2}',
    'text_si_busy': 'Calcolo spazio su disco{127}{128}',
    'text_si_removed': '  *** SD rimossa/USB occupato ***',
    'text_si_maker': 'Produttore SD:   0x{3}, {34}{4}{34}',
    'text_si_product': 'Nome prodotto:   {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'Seriale SD:      {8}, Prod. {9}/{10}',
    'text_si_acc': 'Acc. SD:      {11}.{12} / {13}.{14} ms med/max',
    'text_si_accmeas': 'Acc. SD:      misuro{127}{128}',
    'text_si_usage': 'Uso scheda: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'controllo{127}{128}',
    'text_si_sgb_missing': 'assente',
    'text_si_sgb_mismatch': 'errato',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'Stato CIC: {19}',
    'text_si_clk': 'Clock SNES: {20}Hz',
    'text_si_clkmeas': 'Clock SNES: misuro{127}{128}',
    'text_si_u16on': 'Ultra16 seriale {21} (Autoboot On)',
    'text_si_u16off': 'Ultra16 seriale {21} (Autoboot Off)',
    'text_si_model': 'Modello: {22}',
    'text_si_updatefw': '*** Aggiorna il firmware ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Test memoria',
    'mdesc_mm_memtest': 'Controlla i collegamenti FPGA-RAM (10 s). Il test completo verifica ogni cella (30 s). Riavvia la console.',
    'text_mtl_prompt': 'A: Linee  X: Completo  B: Chiudi',
    'text_mtl_prompt2': 'Entrambi riavviano. X dura 30s.',
    'text_mtl_run': 'Test della memoria, attendere{127}{128}',
    'text_mtl_none': 'Nessun test ancora eseguito.',
    'text_mtl_pass': 'Tutte le linee RAM OK.',
    'text_mtl_fail': 'Guasti rilevati:',
    'text_mtl_nocore': '/sd2snes/fpga_test assente/non valido.',
    'text_mtl_more': '(altri guasti non mostrati)',
    'text_mtl_cellpass': 'Tutte le celle verificate.',
    'text_mtl_cellfail': 'Prima cella difettosa a 0x',
    'text_mtl_cellskip': 'Scansione saltata: correggi linee.',
    'text_mt_data': 'controlla linea dati D',
    'text_mt_addr': 'controlla linea indirizzi A',
    'text_mt_short': 'possibile corto A',
    'text_mt_bytesel': 'controlla LB# / UB#',
    'text_mt_ctrl': 'controlla CE# / OE# / WE#',
    'text_mt_fpgactrl': 'controlla CE#/OE#/WE# FPGA',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'Lettore PCM',
    'text_pcm_prompt': 'A: Play/Pausa   B: Chiudi',
    'text_pcm_promptb': 'B: Chiudi',
    'text_pcm_paused': 'In pausa',
    'text_pcm_erropen': 'Impossibile leggere il file.',
    'text_pcm_errmagic': 'Non è un file PCM MSU-1.',
    'text_pcm_nosup': '*** Aggiorna il firmware ***',
    'text_st_slotb_title': 'Sufami Turbo - Slot B',
    'text_st_slotb_footer': 'A:Gioca  B:Indietro  <>:Pag  LR:Inizio/Fine',
    'text_st_slotb_none': '[Nessuna cartuccia nello Slot B]',
    'text_ips_nopatch': '[Nessuna patch]',
    'text_ips_header': 'Patch',
    'mtext_patch_verify': 'Verifica integrità (~23s)',
    'mtext_patch_clearppu': "Pulisci PPU all'avvio",
    'mdesc_patch_verify': 'Rilegge la ROM patchata per verificarla (caricamento molto più lento)',
    'mdesc_patch_clearppu': "Pulisce VRAM/CGRAM/OAM prima dell'avvio di una ROM patchata (romhack che saltano l'init della PPU)",
    'text_patch_hdr_auto': 'auto  ',
    'text_patch_hdr_on': 'intest',
    'text_patch_hdr_off': 'grezzo',
    'text_patch_footer': 'A:Gioca  Y:Altro  B:Indietro  <>:Pag  LR:Ini/Fine',
    'text_patch_creating': 'Creo la ROM patchata...',
    'text_err_patchexport': 'Impossibile creare ROM',
    'text_patch_export_ok': 'ROM patchata creata',
    'text_patch_export_part': 'ROM ok, dati incompleti',
    'text_patch_export_exists': 'ROM patchata già esistente',
    'text_patch_hdrsel_auto': 'Auto (rileva)',
    'text_patch_hdrsel_on': 'Con header',
    'text_patch_hdrsel_off': 'Senza header',
    'mtext_patch_header_mode': 'Modo header',
    'mdesc_patch_header_mode': 'Come sono letti gli offset IPS: Auto, Header (sposta 512 B) o Grezzo.',
    'mtext_patch_create_rom': 'Crea ROM patchata',
    'mdesc_patch_create_rom': "Scrive la ROM patchata accanto all'originale, col nome del file patch, copiando copertina, salvataggi, cheat e guide. Richiede alcuni minuti.",
    'cheat_tab_head': 'Descrizione                              Attivo',
    'cheat_tab_hint_text': ' A:On/Off Y:Modif Sel:Nuovo B:Esci',
    'mtext_browser_showcov': 'Mostra copertine',
    'mdesc_browser_showcov': 'Mostra le copertine dei giochi nel menu',
    'mtext_browser_covlists': ' {129}Preferiti/Recenti',
    'mdesc_browser_covlists': 'Mostra le copertine anche nelle liste Recenti e Preferiti',
    'mtext_browser_menumusic': 'Musica del menu',
    'mtext_browser_menumusic_random': ' {129}Musica casuale',
    'mtext_browser_menusfx': 'Suoni del menu',
    'mtext_browser_text_outline': 'Contorno del testo',
    'mtext_browser_text_aa': 'Anti-aliasing testo',
    'mdesc_browser_menumusic': 'Riproduce la musica di sottofondo (menu.spc) nel menu',
    'mtext_browser_sortfav': 'Ordina preferiti',
    'mdesc_browser_sortfav': 'Ordina la lista dei preferiti in ordine alfabetico',
    'mtext_browser_restoretheme': 'Ripristina tema',
    'mdesc_browser_restoretheme': 'Riporta il tema del menu a quello predefinito',
    'mtext_browser_restoreclassic': 'Ripristina tema classico',
    'mdesc_browser_restoreclassic': "Carica l'aspetto classico di sd2snes (richiede /sd2snes/classic.thm sulla scheda)",
    'mtext_browser_restoremusic': 'Ripristina musica',
    'mdesc_browser_restoremusic': 'Riporta la musica del menu a quella predefinita (menu.spc)',
    'mdesc_browser_menumusic_random': 'Sceglie uno .spc a caso dalla cartella a ogni carica',
    'mdesc_browser_text_outline': 'Contorno scuro del testo del menu: seguire il tema, o forzare',
    'mdesc_browser_text_aa': 'Bordi morbidi del testo del menu: seguire il tema, o forzare',
    'text_mm_language': 'Lingua',
    'mdesc_mm_language': 'Imposta la lingua del menu/firmware',
    'mdesc_browser_menusfx': 'Riproduce effetti sonori navigando nel menu',
    'mtext_browser_gameinfo': 'Info Gioco',
    'mtext_gameinfo_enable': 'Mostra scheda info',
    'mdesc_browser_gameinfo': 'Mostra copertina, screenshot e info prima di avviare una ROM che ha una voce in /sd2snes/info',
    'mdesc_cfg_gameinfo': "Opzioni della schermata info prima dell'avvio",
    'mtext_browser_gameinfo_video': ' {129}Mostra video',
    'mdesc_browser_gameinfo_video': "Riproduce il filmato animato nella scheda gioco (off mostra un'immagine fissa)",
    'mtext_browser_gameinfo_music': ' {129}Musica del video',
    'mdesc_browser_gameinfo_music': 'Riproduce la colonna sonora del filmato mentre è visibile. Richiede Mostra video.',
    'text_gi_developer': 'Sviluppatore',
    'text_gi_publisher': 'Editore',
    'text_gi_year': 'Anno',
    'text_gi_players': 'Giocatori',
    'text_gi_genre': 'Genere',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Gioca   B: Indietro   Y: Descrizione',
    'text_gi_footer_nav': 'A:Gioca B:Indietro Y:Desc Su/Giù:Gioco',
    'text_gi_footer_full': 'B: Indietro   Su/Giù: Scorri',
    'text_gi_footer_man': 'A: Gioca  B: Indietro  Y: Descrizione  X: Guide',
    'text_gi_footer_nav_man': 'A:Gioca B:Indietro Y:Desc X:Guide Su/Giù:Gioco',
    'text_gi_footer_pick': 'A: Apri   B: Indietro',
    'text_gi_slug_manual': 'Manuale',
    'text_gi_slug_guide': 'Guida',
    'text_gi_slug_map': 'Mappa',
    'text_gi_slug_insert': 'Inserto',
    'text_gi_slug_other': 'Altro',
}
