"""Spanish (Español) strings for the sd2snes menu.

Maps const.a65 string labels -> es text. Accented chars are written as real
UTF-8 here; build_const.py encodes them to the font byte codes.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions ARE rendered now (the selected option's help box) and
localized like the rest; the pool lives in bank $C1 (see build_const.py).
"""

TRANSLATIONS = {
    'text_clkset': 'Ajuste la hora',
    'text_mainmenu': 'Menú Principal',
    'text_mm_file': 'Navegador de Archivos',
    'text_mm_last': 'Juegos Recientes',
    'text_mm_favorites': 'Juegos Favoritos',
    # In-game TAB menu HELP tab (Phase 2)
    'text_igm_hdr_controls': 'ATAJOS EN JUEGO',
    'text_igm_open': 'Abrir este menu',
    'text_igm_save': 'Guardar savestate',
    'text_igm_load': 'Cargar savestate',
    'text_igm_slot': 'Elegir slot',
    'text_igm_reset_game': 'Reset del juego',
    'text_igm_reset': 'Reset al menu',
    'text_igm_cheats_on': 'Activar cheats',
    'text_igm_cheats_off': 'Desactivar cheats',
    'text_igm_hooks_off': 'Desactivar hooks',
    'text_igm_hooks_10s': 'Desactivar hooks 10 s',
    'text_igm_pergame': '* combo propio de este juego (savestate_inputs.yml)',
    'text_igm_hdr_keys': 'TECLAS DEL MENU',
    'text_igm_keys1': 'Izq/Der: pestaña   L/R: primera/última   A: abrir',
    'text_igm_keys2': 'B: atrás   START: cerrar   SELECT: esta ayuda',
    'text_igm_unavail': 'no disponible en este juego',
    'text_igm_key_up': 'Arriba',
    'text_igm_key_down': 'Abajo',
    'text_igm_key_left': 'Izq',
    'text_igm_key_right': 'Der',
    'text_igm_st_title': 'ELEGIR RANURA DE SAVESTATE',
    'text_igm_st_slot': 'RANURA',
    'text_igm_st_full': 'OCUPADA',
    'text_igm_st_empty': 'VACIA',
    'text_igm_st_hint_save': 'guardar',
    'text_igm_st_disabled': 'Ranuras de savestate desactivadas',
    'text_igm_st_hint_load': 'cargar',
    'text_igm_st_unavail': 'Savestates no disponibles en este juego',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'AYUDA',
    'text_igm_tab_manual': 'GUÍAS',
    'text_igm_tab_trainer': 'ENTRENADOR',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    'text_igm_sv_title': 'GUARDADO DE PARTIDA',
    'text_igm_sv_nosram': 'Este juego no tiene guardado de batería',
    'text_igm_sv_file': 'Archivo .srm:',
    'text_igm_sv_exists': 'EXISTE',
    'text_igm_sv_missing': 'NO EXISTE',
    'text_igm_sv_size': 'Tamaño:',
    'text_igm_sv_write': 'Última esc.:',
    'text_igm_sv_autosave': 'Autoguardado:',
    'text_igm_sv_on': 'ACTIVADO',
    'text_igm_sv_off': 'DESACTIVADO',
    'text_igm_sv_hint_on': 'El guardado se escribe automáticamente al jugar',
    'text_igm_sv_hint_off': 'Autoguardado apagado - guarda desde el menú',
    'text_igm_sv_slottitle': 'ELIGE RANURA DE SRAM',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Se aplica en el próximo arranque',
    'text_igm_mn_title': 'MANUAL DEL JUEGO',
    'text_igm_mn_read': 'A: Leer el manual',
    'text_igm_mn_pages': 'páginas',
    'text_igm_mn_notfound': 'Manual no encontrado',
    'text_igm_mn_error': 'Error al cargar el manual',
    'text_igm_mn_guide': 'GUÍA',
    'text_igm_mn_select': 'ELIGE UNA GUÍA',
    'text_igm_mn_keys1': 'A: zoom 2x   L/R: cambia pagina',
    'text_igm_mn_keys2': 'Cruceta: mover   B: volver',
    'text_igm_mn_slug_manual': 'Manual',
    'text_igm_mn_slug_guide': 'Guia',
    'text_igm_mn_slug_map': 'Mapa',
    'text_igm_mn_slug_insert': 'Folleto',
    'text_igm_mn_slug_other': 'Otro',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'ENTRENADOR DE RAM',
    'text_igm_tr_searchtype': 'Tipo búsqueda:',
    'text_igm_tr_datatype': 'Tamaño:',
    'text_igm_tr_value': 'Valor:',
    'text_igm_tr_candidates': 'Candidatos:',
    'text_igm_tr_compare': 'Comparar:',
    'text_igm_tr_exact': 'Valor exacto',
    'text_igm_tr_unknown': 'Desconocido',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Igual a',
    'text_igm_tr_ne': 'Distinto',
    'text_igm_tr_changed': 'Cambió',
    'text_igm_tr_unchanged': 'Sin cambio',
    'text_igm_tr_increased': 'Aumentó',
    'text_igm_tr_decreased': 'Disminuyó',
    'text_igm_tr_gt': 'Mayor que',
    'text_igm_tr_lt': 'Menor que',
    'text_igm_tr_newsearch': 'NUEVA BÚSQUEDA',
    'text_igm_tr_filter': 'FILTRAR',
    'text_igm_tr_results': 'RESULTADOS',
    'text_igm_tr_reset': 'REINICIAR BÚSQUEDA',
    'text_igm_tr_address': 'DIRECCIÓN',
    'text_igm_tr_current': 'ACTUAL',
    'text_igm_tr_setvalue': 'ESCRIBIR VALOR',
    'text_igm_tr_freeze': 'CONGELAR',
    'text_igm_tr_unfreeze': 'DESCONGELAR',
    'text_igm_tr_savecheat': 'GUARDAR CHEAT',
    'text_igm_tr_frozen': 'CONGELADO',
    'text_igm_tr_searching': 'Buscando...',
    'text_igm_tr_noresults': 'Sin resultados',
    'text_igm_tr_toomany': 'Demasiados resultados - filtra más',
    'text_igm_tr_dropped_rst': 'Búsqueda reiniciada - reinicio',
    'text_igm_tr_nofreeze': 'Máximo de 4 congelados',
    'text_igm_tr_hint_setup': 'A: elegir   D-Pad: cambiar',
    'text_igm_tr_hint_edit': 'D-Pad: editar   A: OK   B: salir',
    'text_igm_tr_hint_list': 'A: inspeccionar   B: volver',
    'text_igm_tr_master_off': 'Master de cheats OFF',
    'text_igm_tr_saved': 'Cheat guardado',
    'text_igm_tr_savefail': 'No se pudo guardar el cheat',
    'text_igm_tr_unpin': 'QUITAR DE LA LISTA',
    'mtext_mm_cfg': 'Configuración',
    'mtext_mm_sysinfo': 'Información del Sistema',
    'mtext_cfg_time': 'Ajustar Reloj',
    'mtext_cfg_ask_clock': 'Pedir la hora al iniciar',
    'mtext_cfg_bsx': 'Opciones BS-X',
    'mtext_cfg_browser': 'Opciones del Navegador',
    'mtext_cfg_chip': 'Opciones de Chip',
    'mtext_cfg_sgb': 'Opciones SGB',
    'mtext_cfg_ingame': 'Opciones en Juego',
    'mtext_cfg_savestates': 'Opciones de Savestates',
    'mtext_cfg_scic': 'Opciones SuperCIC',
    'mtext_cfg_patch': 'Opciones de Patches',
    'mtext_bsx_timesource': 'Reloj BS-X',
    'mtext_bsx_time': 'Hora personalizada',
    'mtext_scic_enable': 'Activar SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Modo vídeo menú',
    'mtext_scic_vmode_game': ' {129}Modo vídeo juego',
    'mtext_scic_buscompat': 'Compat. de bus',
    'mtext_browser_sort': 'Ordenar directorios',
    'mtext_browser_hide_ext': 'Ocultar extensiones',
    'mtext_browser_msu_folders': 'Abrir carpetas MSU-1 como juego',
    'mtext_browser_sd2snes_dir': 'Mostrar carpeta sd2snes',
    'mtext_browser_screensaver': 'Protector de pantalla',
    'mtext_browser_screensaver_timeout': 'Atenuar pantalla tras',
    'mtext_browser_ledbright': 'Brillo de los LEDs',
    'mtext_ingame_cheats': 'Iniciar con cheats',
    'mtext_ingame_shortreset': 'Reset al menú',
    'mtext_ingame_enable': 'Hook en juego',
    'mtext_ingame_buttons': ' {129}Botones en juego',
    'mtext_ingame_cheat_overlay': ' {129}Menú dentro del juego',
    'mtext_ingame_game_manual': ' {129}Manual del juego',
    'mtext_ingame_holdoff': ' {129}Espera inicial',
    'mtext_ingame_savestate': 'Savestates en juego',
    'mtext_savestate_slots': ' {129}Ranuras de savestate',
    'mtext_loadstate_delay': ' {129}Retardo de carga',
    'mtext_sgb_enable_hooks': 'Hooks en juego',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'Funciones SGB',
    'mtext_sgb_spr_increase': 'Límite máx. sprites (40)',
    'mtext_sgb_volume_boost': 'Aumento de volumen',
    'mtext_sgb_clock': 'Clock (Timing)',
    'mtext_sgb_bios': 'Versión del BIOS',
    'mtext_ingame_regionpatch': 'Patch auto. de región',
    'mtext_ingame_1chiptransientfixes': 'Correcciones 1CHIP',
    'mtext_ingame_brightlimit': 'Límite de brillo',
    'mtext_ingame_resetpatch': 'Patch de reset (clock)',
    'mtext_ingame_autosave': 'Autoguardado',
    'mtext_ingame_autosave_msu1': ' {129}Autoguardado MSU-1',
    'mtext_chip_cx4_speed': 'Velocidad Cx4',
    'mtext_chip_cc_time_limit': "Timer del Competition Cart (min)",
    'mtext_chip_gsu_speed': 'Velocidad SuperFX',
    'mtext_chip_msu1_volume_boost': 'Aumento volumen MSU-1',
    'mtext_a26_width': 'Ancho de vídeo Atari 2600',
    'mdesc_mm_last': 'Muestra hasta 10 juegos recientes',
    'mdesc_mm_favorites': 'Muestra hasta 20 juegos favoritos',
    'mdesc_mm_cfg': 'Configurar el sd2snes',
    'mdesc_mm_sysinfo': 'Info de FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Ajustar fecha y hora',
    'mdesc_cfg_ask_clock': 'Pide la hora al iniciar mientras el reloj no esté ajustado',
    'mdesc_cfg_bsx': 'Opciones específicas BS-X/Satellaview',
    'mdesc_cfg_browser': 'Cambiar opciones del navegador',
    'mdesc_cfg_chip': 'Funciones especiales de chip',
    'mdesc_cfg_ingame': 'Funciones durante el juego',
    'mdesc_cfg_sgb': 'Funciones del Super Game Boy',
    'mdesc_cfg_savestates': 'Funciones de savestates',
    'mdesc_cfg_scic': 'Activar SuperCIC y modos de vídeo',
    'mdesc_cfg_patch': 'Opciones de parcheo IPS/BPS',
    'mdesc_bsx_timesource': 'Fecha/hora que ven los juegos BS-X',
    'mdesc_bsx_time': 'Hora y fecha personalizadas para BS-X',
    'mdesc_scic_enable': 'Necesario para funciones SuperCIC',
    'mdesc_scic_vmode_menu': 'Modo de vídeo del menú',
    'mdesc_scic_vmode_game': 'Modo de vídeo de los juegos',
    'mdesc_scic_buscompat': 'Timing de bus estrecho para consolas donde algunos juegos se cuelgan o fallan. Actívalo solo si ves bloqueos en esta consola.',
    'mdesc_browser_sort': 'Ordenar listas de archivos',
    'mdesc_browser_hide_ext': 'Ocultar extensiones de archivos',
    'mdesc_browser_msu_folders': 'A en una carpeta con una sola ROM MSU-1 abre el juego',
    'mdesc_browser_sd2snes_dir': 'Muestra /sd2snes en la lista de archivos',
    'mdesc_browser_screensaver': 'Oscurecer la pantalla tras un tiempo',
    'mdesc_browser_screensaver_timeout': 'Tiempo para oscurecer la pantalla',
    'mdesc_browser_ledbright': 'Cambiar brillo de los LEDs',
    'mdesc_ingame_cheats': 'Iniciar con cheats activados. Se puede cambiar con los botones en juego',
    'mdesc_ingame_shortreset': 'Adónde lleva el reset. Carpeta/ROM reabren la carpeta del último juego. Duración: pulsación corta resetea el juego, larga va a la ROM.',
    'mdesc_ingame_enable': 'Necesario para botones en juego y cheats 7E/7F',
    'mdesc_ingame_buttons': 'Botones en juego (reset, activar/desactivar cheats{127}{128}). Requiere el hook activado.',
    'mdesc_ingame_cheat_overlay': 'Menú dentro del juego (manten L+R+Y+Izq): cheats, savestates, saves y guías. Requiere hook. No disponible en algunos chips especiales.',
    'mdesc_ingame_game_manual': 'Muestra el manual del juego en el menú en juego. Requiere <rom>.man en /sd2snes/info.',
    'mdesc_ingame_holdoff': 'Espera 10 segundos antes de activar el hook (ayuda a algunos juegos a arrancar con el hook activado)',
    'mdesc_ingame_savestate': 'Activar savestates en juego y elegir mando. Predet.: Guardar - Start+R / Cargar - Start+L',
    'mdesc_savestate_slots': 'Activar ranuras de savestate. Select+Dpad: cada dirección es una ranura',
    'mdesc_loadstate_delay': 'Ajustar el retardo de carga de savestate (frames)',
    'mdesc_sgb_enable_hooks': 'Necesario para los botones en juego',
    'mdesc_sgb_enable_state': 'Activar savestates internos en SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Desactivar/activar las mejoras SGB',
    'mdesc_sgb_spr_increase': 'Aumentar el número de sprites visibles',
    'mdesc_sgb_volume_boost': 'Aumentar volumen del audio SGB si es muy bajo',
    'mdesc_sgb_clock': 'Ajusta el clock del SGB (timing)',
    'mdesc_sgb_bios': 'Seleccionar una versión de firmware/BIOS del SGB',
    'mdesc_ingame_regionpatch': 'Evita la protección simple de región de los juegos',
    'mdesc_ingame_1chiptransientfixes': 'Corrige glitches de brillo, líneas y sombras en consolas 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limitar el brillo general (p. ej. en consolas 1CHIP para niveles RGB)',
    'mdesc_ingame_resetpatch': 'Activar patch de reset para alinear clocks. Corrige fallos gráficos en algunos juegos',
    'mdesc_ingame_autosave': 'Guardar SRM automáticamente cuando cambia la Save RAM',
    'mdesc_ingame_autosave_msu1': 'MSU-1: aprovecha pausas para autoguardar SRM. Puede causar breves cortes.',
    'mdesc_chip_cx4_speed': 'Velocidad del soft core Cx4',
    'mdesc_chip_cc_time_limit': "Temporizador de ronda de los cartuchos de evento (Campus Challenge '92, PowerFest '94)",
    'mdesc_chip_gsu_speed': 'Velocidad del soft core SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Aumento de volumen MSU-1 si tu sd2snes suena muy bajo (Rev. E-G)',
    'mdesc_a26_width': 'Ancho de imagen del Atari 2600: 160 es nativo 1:1, 256 llena la pantalla',
    'mdesc_cx4_speed_fast': 'Ejecutar lo más rápido posible',
    'mdesc_cx4_speed_normal': 'Ejecutar aprox. a la velocidad original',
    'mdesc_gsu_speed_fast': 'Ejecutar lo más rápido posible',
    'mdesc_gsu_speed_normal': 'Ejecutar aprox. a la velocidad original',
    'text_filesel_selected_file': 'Archivo seleccionado',
    'text_filesel_context_add_to_favorites': 'Añadir a favoritos',
    'mdesc_filesel_context_add_to_favorites': 'Añade el archivo seleccionado a favoritos',
    'text_filesel_context_remove_from_favorites': 'Quitar de favoritos',
    'mdesc_filesel_context_remove_from_favorites': 'Quita el archivo seleccionado de favoritos',
    'text_recent_context_remove_from_recent': 'Quitar de recientes',
    'mdesc_recent_context_remove_from_recent': 'Quita el archivo de la lista de recientes',
    'text_filesel_set_as_autoboot': 'Definir como autoboot',
    'mdesc_filesel_set_as_autoboot': 'Arranca esta ROM en el próximo encendido (mantén START para cancelar)',
    'text_filesel_set_as_bgm': 'Definir como música del menú',
    'mdesc_filesel_set_as_bgm': 'Usar este SPC como música de fondo del menú',
    'text_filesel_context_delete_file': 'Eliminar',
    'mdesc_filesel_context_delete_file': 'Elimina el archivo seleccionado',
    'text_filesel_context_delete_srm': 'Eliminar save',
    'mdesc_filesel_context_delete_srm': 'Elimina el archivo de save SRM para esta ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Visualizar, activar o desactivar cheats del archivo YAML de esta ROM',
    'text_filesel_context_gameinfo': 'Info del juego',
    'mdesc_filesel_context_gameinfo': 'Muestra la info de este juego (carátula, captura y datos) antes de jugar',
    'text_cheat_yes': 'Sí',
    'text_cheat_no': 'No',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Nombre',
    'text_cheat_none_msg': 'No hay cheats para esta ROM',
    'text_confirm_delete_file': '¿Borrar este archivo?',
    'text_confirm_delete_srm': '¿Borrar el archivo de guardado?',
    'text_confirm_hint': 'A:Confirmar  B:Cancelar',
    'text_confirm_no_sel': '[No]',
    'text_confirm_no_unsel': ' No ',
    'text_confirm_yes_sel': '[Sí]',
    'text_confirm_yes_unsel': ' Sí ',
    'text_statusbar_play': 'A:Jugar B:Atrás X:Menú',
    'text_statusbar_keys': 'A:OK B:Atrás X:Menú Y:Contexto',
    'text_statusbar_spc': 'B:Atrás',
    'text_statusbar_menu': 'A:OK B:Atrás',
    'text_last': 'Juegos recientes',
    'text_favorite': 'Juegos favoritos',
    'text_no_last': 'Sin recientes',
    'text_no_favorite': 'Sin favoritos',
    'text_favorites_full': 'Favoritos lleno',
    'text_err_supplfile': 'Archivo no hallado:',
    'text_err_noimpl': 'Chip no soportado:',
    'text_err_nohw': 'Requiere hardware Mk.III:',
    'text_err_generic': 'Error al cargar:',
    'text_on_p1': 'Sí: P1',
    'text_on_p2': 'Sí: P2',
    'text_on': 'Sí',
    'text_off': 'No',
    'text_15_max': '15 (máx)',
    'text_theme': 'Tema',
    'text_cover_large': 'Grande',
    'text_cover_small': 'Pequeño',
    'text_gameinfo_context': 'Contexto',
    'text_nav_folder': 'Carpeta',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Duración',
    'text_enabled': 'Activo',
    'text_disabled': 'Inactivo',
    'text_normal': 'Normal',
    'text_fast': 'Rápido',
    'text_a26_w256': '256 (ancho)',
    'text_rtc': 'Tiempo real',
    'text_custom': 'Person.',
    'text_yes': 'Sí',
    'text_no': 'No',
    'text_auto': 'Auto',
    'text_add': 'Añadir',
    'text_remove': 'Quitar',
    'text_edit': 'Editar',
    'text_save': 'Guardar',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 hora',
    'text_spcplay': 'Reproductor de SPC',
    'text_spcload': 'Cargando SPC en SPC700{127}{128}    ',
    'text_spcstarta': '**** Reproduciendo SPC ****',
    'text_spcstartb': 'Nombre:',
    'text_spcstartc': 'Canción:',
    'text_spcstartd': 'Artista:',
    'text_spc_statusbar': 'B:Atrás',
    'text_loading': 'Cargando{127}{128}                       ',
    'text_saving': 'Guardando{127}{128}                      ',
    # Window title prefix for the cheat list, composed by the menu. "Cheats" is kept
    # as-is in every language on purpose; only the preposition is localized.
    'text_cheat': 'Cheats para ',
    'text_cheat_noname': '(sin nombre)',
    'text_igm_cheat_noname': '(sin nombre)',
    'text_igm_ch_none': 'Sin cheats',
    'text_igm_ft_tab': '<>:PESTANA L/R:EXTREMOS A:ABRIR SEL:AYUDA B:CERRAR',
    'text_igm_ft_cheats': 'A:SI/NO Y:EDITAR SEL:NUEVO X:CHEATS B:ATRAS',
    'text_igm_ft_generic': 'A:SELECCIONAR B:ATRAS',
    'text_igm_master_on': 'CHEATS: SI',
    'text_igm_master_off': 'CHEATS: NO',
    'text_igm_ft_ce_edit': 'A:EDITAR SEL:+CODIGO Y:QUITAR B:ATRAS',
    'text_igm_ft_ce_kbd': 'A:ESCRIBIR Y:BORRAR SEL:ESPACIO X:OK B:CANCELAR',
    'text_igm_ft_help': 'B:ATRAS START:CERRAR',
    'text_igm_ce_title_new': 'NUEVO CHEAT',
    'text_igm_ce_title_edit': 'EDITAR CHEAT',
    'text_igm_ce_name': 'Nombre:',
    'text_igm_ce_save': 'GUARDAR',
    'text_igm_ce_delete': 'BORRAR CHEAT',
    'text_igm_ce_confirm': '¿Borrar este cheat?',
    'text_igm_ce_confirm_keys': 'A: sí   B: no',
    'text_igm_ce_nosup': 'Actualice el firmware',
    'text_igm_ce_full': 'La lista de cheats está llena',
    'text_igm_ce_badcode': 'Código inválido',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Versión firmware: {2}',
    'text_si_busy': 'Calculando espacio en disco{127}{128}',
    'text_si_removed': '   *** SD extraído/USB ocupado ***',
    'text_si_maker': 'Fabricante SD:   0x{3}, {34}{4}{34}',
    'text_si_product': 'Nombre producto: {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'Serial SD:       {8}, Fab. {9}/{10}',
    'text_si_acc': 'Acceso SD:    {11}.{12} / {13}.{14} ms med/máx',
    'text_si_accmeas': 'Acceso SD:    midiendo{127}{128}',
    'text_si_usage': 'Uso del SD: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'leyendo{127}{128}',
    'text_si_sgb_missing': 'ausente',
    'text_si_sgb_mismatch': 'erróneo',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'Estado CIC: {19}',
    'text_si_clk': 'Clock SNES: {20}Hz',
    'text_si_clkmeas': 'Clock SNES: midiendo{127}{128}',
    'text_si_u16on': 'Ultra16 serie {21} (Autoboot activo)',
    'text_si_u16off': 'Ultra16 serie {21} (Autoboot inactivo)',
    'text_si_model': 'Modelo: {22}',
    'text_si_updatefw': '*** Actualice el firmware ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Prueba de memoria',
    'mdesc_mm_memtest': 'Comprueba el cableado FPGA-RAM (10 s). La prueba completa verifica cada celda (30 s). Reinicia la consola.',
    'text_mtl_prompt': 'A: Probar líneas  X: Todo  B: Cerrar',
    'text_mtl_prompt2': 'Ambos reinician la consola. X: 30s.',
    'text_mtl_run': 'Probando la memoria, espera{127}{128}',
    'text_mtl_none': 'Aún no se ha hecho ninguna prueba.',
    'text_mtl_pass': 'Todas las líneas de RAM OK.',
    'text_mtl_fail': 'Fallos encontrados:',
    'text_mtl_nocore': '/sd2snes/fpga_test ausente/no válido.',
    'text_mtl_more': '(más fallos no mostrados)',
    'text_mtl_cellpass': 'Todas las celdas verificadas.',
    'text_mtl_cellfail': 'Primera celda mala en 0x',
    'text_mtl_cellskip': 'Escaneo omitido: corrige las líneas.',
    'text_mt_data': 'ver línea de datos D',
    'text_mt_addr': 'ver línea de direcciones A',
    'text_mt_short': 'posible corto A',
    'text_mt_bytesel': 'ver LB# / UB#',
    'text_mt_ctrl': 'ver CE# / OE# / WE#',
    'text_mt_fpgactrl': 'ver CE# / OE# / WE# de la FPGA',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'Reproductor PCM',
    'text_pcm_prompt': 'A: Reproducir/Pausar   B: Cerrar',
    'text_pcm_promptb': 'B: Cerrar',
    'text_pcm_paused': 'En pausa',
    'text_pcm_erropen': 'No se pudo leer el archivo.',
    'text_pcm_errmagic': 'No es un archivo PCM de MSU-1.',
    'text_pcm_nosup': '*** Actualiza el firmware ***',
    'text_st_slotb_title': 'Sufami Turbo - Ranura B',
    'text_st_slotb_footer': 'A:Jugar  B:Volver  <>:Pag  LR:Ini/Fin',
    'text_st_slotb_none': '[Sin cartucho en Ranura B]',
    'text_ips_nopatch': '[Sin patch]',
    'text_ips_header': 'Parches',
    'mtext_patch_verify': 'Verificar Integridad (~23s)',
    'mtext_patch_clearppu': 'Limpiar PPU al arrancar',
    'mdesc_patch_verify': 'Relee la ROM parcheada para verificarla (carga mucho más lenta)',
    'mdesc_patch_clearppu': 'Borra VRAM/CGRAM/OAM antes de arrancar una ROM parcheada (romhacks que omiten el init de PPU)',
    'text_patch_hdr_auto': 'auto  ',
    'text_patch_hdr_on': 'cabec.',
    'text_patch_hdr_off': 'crudo ',
    'text_patch_footer': 'A:Jugar  Y:Mas  B:Volver  <>:Pag  LR:Ini/Fin',
    'text_patch_creating': 'Creando ROM con parche...',
    'text_err_patchexport': 'No se pudo crear la ROM',
    'text_patch_export_ok': 'ROM con parche creada',
    'text_patch_export_part': 'ROM ok, assets incompletos',
    'text_patch_export_exists': 'ROM con parche ya existe',
    'text_patch_hdrsel_auto': 'Auto (detectar)',
    'text_patch_hdrsel_on': 'Con cabecera',
    'text_patch_hdrsel_off': 'Sin cabecera',
    'mtext_patch_header_mode': 'Modo de cabecera',
    'mdesc_patch_header_mode': 'Cómo se leen los offsets del IPS: Auto, Cabecera (desplaza 512 B) o Crudo.',
    'mtext_patch_create_rom': 'Crear ROM con parche',
    'mdesc_patch_create_rom': 'Escribe la ROM con el parche aplicado junto a la original, copiando portada, partidas, cheats y guías. Puede tardar varios minutos.',
    'cheat_tab_head': 'Nombre                                    Activo',
    'cheat_tab_hint_text': ' A:On/Off Y:Editar Sel:Nuevo B:Fin',
    'mtext_browser_showcov': 'Mostrar carátulas',
    'mdesc_browser_showcov': 'Mostrar las carátulas de los juegos en el menú',
    'mtext_browser_covlists': ' {129}Favoritos/Recientes',
    'mdesc_browser_covlists': 'Mostrar carátulas también en las listas Recientes y Favoritos',
    'mtext_browser_menumusic': 'Música del menú',
    'mtext_browser_menumusic_random': ' {129}Música aleatoria',
    'mtext_browser_menusfx': 'Sonidos del menú',
    'mtext_browser_text_outline': 'Contorno del texto',
    'mtext_browser_text_aa': 'Suavizado del texto',
    'mdesc_browser_menumusic': 'Reproducir música de fondo (menu.spc) en el menú',
    'mtext_browser_sortfav': 'Ordenar favoritos',
    'mdesc_browser_sortfav': 'Ordenar la lista de favoritos alfabéticamente',
    'mtext_browser_restoretheme': 'Restaurar tema',
    'mdesc_browser_restoretheme': 'Restaurar el tema del menú al predeterminado',
    'mtext_browser_restoreclassic': 'Restaurar tema clásico',
    'mdesc_browser_restoreclassic': 'Cargar el aspecto clásico de sd2snes (requiere /sd2snes/classic.thm en la tarjeta)',
    'mtext_browser_restoremusic': 'Restaurar música',
    'mdesc_browser_restoremusic': 'Restaurar la música del menú al predeterminado (menu.spc)',
    'mdesc_browser_menumusic_random': 'Elige un .spc al azar de la carpeta en cada carga',
    'mdesc_browser_text_outline': 'Contorno oscuro del texto del menú: seguir el tema, o forzar',
    'mdesc_browser_text_aa': 'Bordes suaves del texto del menú: seguir el tema, o forzar',
    'text_mm_language': 'Idioma',
    'mdesc_mm_language': 'Definir el idioma del menú/firmware',
    'mdesc_browser_menusfx': 'Reproducir efectos de sonido al navegar por el menú',
    'mtext_browser_gameinfo': 'Info del Juego',
    'mtext_gameinfo_enable': 'Mostrar pantalla de info',
    'mdesc_browser_gameinfo': 'Muestra carátula, captura e info antes de iniciar una ROM que tenga una entrada en /sd2snes/info',
    'mdesc_cfg_gameinfo': 'Opciones de la pantalla de info del juego (antes de iniciar)',
    'mtext_browser_gameinfo_video': ' {129}Mostrar vídeo',
    'mdesc_browser_gameinfo_video': 'Reproduce el clip animado en la ficha (apagado muestra una captura estática)',
    'mtext_browser_gameinfo_music': ' {129}Música del vídeo',
    'mdesc_browser_gameinfo_music': 'Reproduce la música del vídeo mientras se muestra el clip. Requiere Mostrar vídeo.',
    'text_gi_developer': 'Desarrollador',
    'text_gi_publisher': 'Distribuidora',
    'text_gi_year': 'Año',
    'text_gi_players': 'Jugadores',
    'text_gi_genre': 'Género',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Jugar  B: Volver  Y: Descripción',
    'text_gi_footer_nav': 'A:Jugar B:Volver Y:Desc Arr/Abj:Juego',
    'text_gi_footer_full': 'B: Volver  Arriba/Abajo: Desplazar',
    'text_gi_footer_man': 'A: Jugar  B: Volver  Y: Descripción  X: Guías',
    'text_gi_footer_nav_man': 'A:Jugar B:Volver Y:Desc X:Guías Arr/Abj:Juego',
    'text_gi_footer_pick': 'A: Abrir  B: Volver',
    'text_gi_slug_manual': 'Manual',
    'text_gi_slug_guide': 'Guia',
    'text_gi_slug_map': 'Mapa',
    'text_gi_slug_insert': 'Folleto',
    'text_gi_slug_other': 'Otro',
}
