"""German (Deutsch) strings for the sd2snes menu.

Maps const.a65 string labels -> de text. The current menu font lacks some
German glyphs, so those characters are written as ae/oe/ue/ss for predictable rendering.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions ARE rendered now (the selected option's help box) and
localized like the rest; the pool lives in bank $C1 (see build_const.py).
"""

TRANSLATIONS = {
    'text_clkset': 'Bitte Uhrzeit einstellen',
    'text_mainmenu': 'Hauptmenue',
    'text_mm_file': 'Dateibrowser',
    'text_mm_last': 'Letzte Spiele',
    'text_mm_favorites': 'Favoriten',
    # In-game TAB menu HELP tab (Phase 2). Umlauts transliterated (ae/oe/ue/ss):
    # the accent table has no oe/ae/ss glyphs, matching the mtext_* convention.
    'text_igm_hdr_controls': 'TASTENKUERZEL IM SPIEL',
    'text_igm_open': 'Dieses Menue oeffnen',
    'text_igm_save': 'Savestate sichern',
    'text_igm_load': 'Savestate laden',
    'text_igm_slot': 'Slot waehlen',
    'text_igm_reset_game': 'Spiel neu starten',
    'text_igm_reset': 'Zum Menue',
    'text_igm_cheats_on': 'Cheats an',
    'text_igm_cheats_off': 'Cheats aus',
    'text_igm_hooks_off': 'Hooks aus',
    'text_igm_hooks_10s': 'Hooks aus fuer 10 s',
    'text_igm_pergame': '* Combo dieses Spiels (savestate_inputs.yml)',
    'text_igm_hdr_keys': 'MENUETASTEN',
    'text_igm_keys1': 'Links/Rechts: Tab   L/R: Anfang/Ende   A: oeffnen',
    'text_igm_keys2': 'B: zurueck   START: schliessen   SELECT: diese Hilfe',
    'text_igm_unavail': 'hier nicht verfuegbar',
    'text_igm_key_up': 'Hoch',
    'text_igm_key_down': 'Runter',
    'text_igm_key_left': 'Links',
    'text_igm_key_right': 'Rechts',
    'text_igm_st_title': 'SAVESTATE-SLOT WAEHLEN',
    'text_igm_st_slot': 'SLOT',
    'text_igm_st_full': 'BELEGT',
    'text_igm_st_empty': 'LEER',
    'text_igm_st_hint_save': 'sichern',
    'text_igm_st_disabled': 'Savestate-Slots deaktiviert',
    'text_igm_st_hint_load': 'laden',
    'text_igm_st_unavail': 'Savestates fuer dieses Spiel nicht verfuegbar',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'HILFE',
    'text_igm_tab_manual': 'GUIDES',
    'text_igm_tab_trainer': 'TRAINER',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    # No umlauts/ss (follow the de convention: ae/oe/ue/ss).
    'text_igm_sv_title': 'SPIELSTAND',
    'text_igm_sv_nosram': 'Dieses Spiel hat keinen Batterie-Speicher',
    'text_igm_sv_file': '.srm-Datei:',
    'text_igm_sv_exists': 'VORHANDEN',
    'text_igm_sv_missing': 'FEHLT',
    'text_igm_sv_size': 'Groesse:',
    'text_igm_sv_write': 'Zuletzt:',
    'text_igm_sv_autosave': 'Autospeich.:',
    'text_igm_sv_on': 'AN',
    'text_igm_sv_off': 'AUS',
    'text_igm_sv_hint_on': 'Speichern erfolgt automatisch beim Spielen',
    'text_igm_sv_hint_off': 'Auto-Speichern aus - im Spielmenue speichern',
    'text_igm_sv_slottitle': 'SRAM-SLOT WAEHLEN',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Gilt beim naechsten Spielstart',
    'text_igm_mn_title': 'SPIELHANDBUCH',
    'text_igm_mn_read': 'A: Handbuch lesen',
    'text_igm_mn_pages': 'Seiten',
    'text_igm_mn_notfound': 'Handbuch nicht gefunden',
    'text_igm_mn_error': 'Fehler beim Laden des Handbuchs',
    'text_igm_mn_guide': 'LEITFADEN',
    'text_igm_mn_select': 'LEITFADEN WAEHLEN',
    'text_igm_mn_keys1': 'A: Zoom 2x   L/R: Seite wechseln',
    'text_igm_mn_keys2': 'Steuerkreuz: schwenken   B: zurueck',
    'text_igm_mn_slug_manual': 'Handbuch',
    'text_igm_mn_slug_guide': 'Anleitung',
    'text_igm_mn_slug_map': 'Karte',
    'text_igm_mn_slug_insert': 'Beilage',
    'text_igm_mn_slug_other': 'Sonstiges',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'RAM-TRAINER',
    'text_igm_tr_searchtype': 'Suchtyp:',
    'text_igm_tr_datatype': 'Datentyp:',
    'text_igm_tr_value': 'Wert:',
    'text_igm_tr_candidates': 'Kandidaten:',
    'text_igm_tr_compare': 'Vergleich:',
    'text_igm_tr_exact': 'Genauer Wert',
    'text_igm_tr_unknown': 'Unbekannt',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Gleich',
    'text_igm_tr_ne': 'Ungleich',
    'text_igm_tr_changed': 'Geändert',
    'text_igm_tr_unchanged': 'Unverändert',
    'text_igm_tr_increased': 'Größer',
    'text_igm_tr_decreased': 'Kleiner',
    'text_igm_tr_gt': 'Größer als',
    'text_igm_tr_lt': 'Kleiner als',
    'text_igm_tr_newsearch': 'NEUE SUCHE',
    'text_igm_tr_filter': 'FILTERN',
    'text_igm_tr_results': 'ERGEBNISSE',
    'text_igm_tr_reset': 'SUCHE ZURÜCKSETZEN',
    'text_igm_tr_address': 'ADRESSE',
    'text_igm_tr_current': 'AKTUELL',
    'text_igm_tr_setvalue': 'WERT SETZEN',
    'text_igm_tr_freeze': 'EINFRIEREN',
    'text_igm_tr_unfreeze': 'AUFTAUEN',
    'text_igm_tr_savecheat': 'CHEAT SPEICHERN',
    'text_igm_tr_frozen': 'EINGEFROREN',
    'text_igm_tr_searching': 'Suche läuft...',
    'text_igm_tr_noresults': 'Keine Treffer',
    'text_igm_tr_toomany': 'Zu viele Treffer - nochmal filtern',
    'text_igm_tr_dropped_rst': 'Suche verworfen - Konsolen-Reset',
    'text_igm_tr_nofreeze': 'Maximal 4 eingefroren',
    'text_igm_tr_hint_setup': 'A: wählen   D-Pad: ändern',
    'text_igm_tr_hint_edit': 'D-Pad: ändern   A: OK   B: zurück',
    'text_igm_tr_hint_list': 'A: ansehen   B: zurück',
    'text_igm_tr_master_off': 'Cheat-Master ist AUS',
    'text_igm_tr_saved': 'Cheat gespeichert',
    'text_igm_tr_savefail': 'Cheat nicht gespeichert',
    'text_igm_tr_unpin': 'AUS LISTE ENTFERNEN',
    'mtext_mm_cfg': 'Einstellungen',
    'mtext_mm_sysinfo': 'Systeminfo',
    'mtext_cfg_time': 'Uhr stellen',
    'mtext_cfg_ask_clock': 'Uhr beim Start abfragen',
    'mtext_cfg_bsx': 'BS-X Optionen',
    'mtext_cfg_browser': 'Browser-Optionen',
    'mtext_cfg_chip': 'Chip-Optionen',
    'mtext_cfg_sgb': 'SGB Optionen',
    'mtext_cfg_ingame': 'Im-Spiel Optionen',
    'mtext_cfg_savestates': 'Savestate-Optionen',
    'mtext_cfg_scic': 'SuperCIC Optionen',
    'mtext_cfg_patch': 'Patch-Optionen',
    'mtext_bsx_timesource': 'BS-X Uhr',
    'mtext_bsx_time': 'Eigene Zeit',
    'mtext_scic_enable': 'SuperCIC aktivieren',
    'mtext_scic_vmode_menu': ' {129}Video-Modus Menue',
    'mtext_scic_vmode_game': ' {129}Video-Modus Spiel',
    'mtext_scic_buscompat': 'Bus-Timing-Kompat.',
    'mtext_browser_sort': 'Ordner sortieren',
    'mtext_browser_hide_ext': 'Endungen ausblenden',
    'mtext_browser_msu_folders': 'MSU-1-Ordner als Spiel öffnen',
    'mtext_browser_sd2snes_dir': 'sd2snes-Ordner zeigen',
    'mtext_browser_screensaver': 'Bildschirmschoner',
    'mtext_browser_screensaver_timeout': 'Abdunkeln nach',
    'mtext_browser_ledbright': 'LED-Helligkeit',
    'mtext_ingame_cheats': 'Mit Cheats starten',
    'mtext_ingame_shortreset': 'Reset zum Menue',
    'mtext_ingame_enable': 'Im-Spiel Hook',
    'mtext_ingame_buttons': ' {129}Im-Spiel Tasten',
    'mtext_ingame_cheat_overlay': ' {129}Menue im Spiel',
    'mtext_ingame_game_manual': ' {129}Spielhandbuch',
    'mtext_ingame_holdoff': ' {129}Start-Wartezeit',
    'mtext_ingame_savestate': 'Im-Spiel Savestates',
    'mtext_savestate_slots': ' {129}Savestate-Slots',
    'mtext_loadstate_delay': ' {129}Ladeverzoegerung',
    'mtext_sgb_enable_hooks': 'Im-Spiel Hooks',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'SGB Funktionen',
    'mtext_sgb_spr_increase': 'Sprite-Limit (40)',
    'mtext_sgb_volume_boost': 'Lautstaerke-Boost',
    'mtext_sgb_clock': 'Takt (Timing)',
    'mtext_sgb_bios': 'BIOS-Version',
    'mtext_ingame_regionpatch': 'Auto-Regionpatch',
    'mtext_ingame_1chiptransientfixes': '1CHIP Korrekturen',
    'mtext_ingame_brightlimit': 'Helligkeitslimit',
    'mtext_ingame_resetpatch': 'Reset-Patch (Takt)',
    'mtext_ingame_autosave': 'Auto-Speichern',
    'mtext_ingame_autosave_msu1': ' {129}MSU-1 Auto-Speich.',
    'mtext_chip_cx4_speed': 'Cx4 Geschwindigkeit',
    'mtext_chip_cc_time_limit': "Competition-Cart-Timer (min)",
    'mtext_chip_gsu_speed': 'SuperFX Geschw.',
    'mtext_chip_msu1_volume_boost': 'MSU-1 Lautstaerke',
    'mtext_a26_width': 'Atari 2600 Bildbreite',
    'mdesc_mm_last': 'Zeigt bis zu 10 zuletzt gespielte Spiele',
    'mdesc_mm_favorites': 'Zeigt bis zu 20 Favoriten',
    'mdesc_mm_cfg': 'sd2snes konfigurieren',
    'mdesc_mm_sysinfo': 'Info zu FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Datum und Uhrzeit einstellen',
    'mdesc_cfg_ask_clock': 'Fragt beim Start nach der Zeit, solange die Uhr ungestellt ist',
    'mdesc_cfg_bsx': 'BS-X/Satellaview-spezifische Optionen',
    'mdesc_cfg_browser': 'Optionen des Dateibrowsers aendern',
    'mdesc_cfg_chip': 'Spezialchip-Funktionen einstellen',
    'mdesc_cfg_ingame': 'Funktionen waehrend des Spiels einstellen',
    'mdesc_cfg_sgb': 'Super Game Boy Funktionen einstellen',
    'mdesc_cfg_savestates': 'Savestate-Funktionen einstellen',
    'mdesc_cfg_scic': 'SuperCIC und Videomodi einstellen',
    'mdesc_cfg_patch': 'Optionen fuer IPS/BPS Patches',
    'mdesc_bsx_timesource': 'Datum/Uhrzeit fuer BS-X Spiele',
    'mdesc_bsx_time': 'Eigene Uhrzeit und eigenes Datum fuer BS-X',
    'mdesc_scic_enable': 'Noetig fuer SuperCIC-Funktionen',
    'mdesc_scic_vmode_menu': 'Videomodus des Menues',
    'mdesc_scic_vmode_game': 'Videomodus der Spiele',
    'mdesc_scic_buscompat': 'Engeres Bus-Timing für Konsolen, auf denen manche Spiele hängen oder Grafikfehler zeigen. Nur aktivieren, wenn Abstürze auftreten.',
    'mdesc_browser_sort': 'Dateilisten sortieren',
    'mdesc_browser_hide_ext': 'Dateiendungen ausblenden',
    'mdesc_browser_msu_folders': 'A auf einem Ordner mit nur einer MSU-1-ROM öffnet das Spiel',
    'mdesc_browser_sd2snes_dir': 'Zeigt /sd2snes in der Dateiliste',
    'mdesc_browser_screensaver': 'Bild nach einer Zeit abdunkeln',
    'mdesc_browser_screensaver_timeout': 'Zeit bis zum Abdunkeln',
    'mdesc_browser_ledbright': 'LED-Helligkeit aendern',
    'mdesc_ingame_cheats': 'Mit aktivierten Cheats starten',
    'mdesc_ingame_shortreset': 'Wohin ein Reset führt. Ordner/ROM öffnen den letzten Spielordner. Dauer: kurz setzt das Spiel zurück, lang führt zur ROM.',
    'mdesc_ingame_enable': 'Noetig fuer Im-Spiel Tasten und 7E/7F Cheats',
    'mdesc_ingame_buttons': 'Im-Spiel Tasten (Reset, Cheats{127}{128}). Benoetigt Hook.',
    'mdesc_ingame_cheat_overlay': 'Menue im Spiel (L+R+Y+Links halten): Cheats, Savestates, Saves, Guides. Benoetigt Hook. Bei einigen Spezialchips nicht verfuegbar.',
    'mdesc_ingame_game_manual': 'Zeigt das Spielhandbuch im Ingame-Menue. Benoetigt <rom>.man in /sd2snes/info.',
    'mdesc_ingame_holdoff': '10 Sekunden warten, bevor der Hook aktiviert wird',
    'mdesc_ingame_savestate': 'Savestates im Spiel aktivieren',
    'mdesc_savestate_slots': 'Savestate-Slots aktivieren. Select+Dpad waehlt Slot',
    'mdesc_loadstate_delay': 'Savestate-Ladeverzoegerung einstellen (Frames)',
    'mdesc_sgb_enable_hooks': 'Noetig fuer Im-Spiel Tasten',
    'mdesc_sgb_enable_state': 'Interne Savestates in SGB2 aktivieren (XR, XL)',
    'mdesc_sgb_enh_override': 'SGB-Erweiterungen aus-/einschalten',
    'mdesc_sgb_spr_increase': 'Mehr sichtbare Sprites erlauben',
    'mdesc_sgb_volume_boost': 'SGB-Audio lauter machen',
    'mdesc_sgb_clock': 'SGB-Takt einstellen (Timing)',
    'mdesc_sgb_bios': 'SGB Firmware/BIOS-Version auswaehlen',
    'mdesc_ingame_regionpatch': 'Einfache Regionssperren umgehen',
    'mdesc_ingame_1chiptransientfixes': 'Helligkeitsfehler auf 1CHIP/Jr. korrigieren',
    'mdesc_ingame_brightlimit': 'Gesamthelligkeit begrenzen',
    'mdesc_ingame_resetpatch': 'Reset-Patch fuer Taktausrichtung aktivieren',
    'mdesc_ingame_autosave': 'SRM automatisch speichern, wenn es sich aendert',
    'mdesc_ingame_autosave_msu1': 'MSU-1: SRM in Pausen speichern. Kann kurz stocken.',
    'mdesc_chip_cx4_speed': 'Geschwindigkeit des Cx4 Softcores',
    'mdesc_chip_cc_time_limit': "Runden-Timer der Event-Module (Campus Challenge '92, PowerFest '94)",
    'mdesc_chip_gsu_speed': 'Geschwindigkeit des SuperFX Softcores',
    'mdesc_chip_msu1_volume_boost': 'MSU-1 Lautstaerke-Boost',
    'mdesc_a26_width': 'Atari-2600-Bildbreite: 160 ist nativ 1:1, 256 fuellt den Bildschirm',
    'mdesc_cx4_speed_fast': 'So schnell wie moeglich ausfuehren',
    'mdesc_cx4_speed_normal': 'Etwa mit Originalgeschwindigkeit ausfuehren',
    'mdesc_gsu_speed_fast': 'So schnell wie moeglich ausfuehren',
    'mdesc_gsu_speed_normal': 'Etwa mit Originalgeschwindigkeit ausfuehren',
    'text_filesel_selected_file': 'Gewaehlte Datei',
    'text_filesel_context_add_to_favorites': 'Zu Favoriten',
    'mdesc_filesel_context_add_to_favorites': 'Datei zu Favoriten hinzufuegen',
    'text_filesel_context_remove_from_favorites': 'Aus Favoriten entfernen',
    'mdesc_filesel_context_remove_from_favorites': 'Datei aus Favoriten entfernen',
    'text_recent_context_remove_from_recent': 'Aus letzten entfernen',
    'mdesc_recent_context_remove_from_recent': 'Datei aus letzter Liste entfernen',
    'text_filesel_set_as_autoboot': 'Als Autoboot setzen',
    'mdesc_filesel_set_as_autoboot': 'Diese ROM beim naechsten Einschalten starten',
    'text_filesel_set_as_bgm': 'Als Menuemusik setzen',
    'mdesc_filesel_set_as_bgm': 'Dieses SPC als Menue-Hintergrundmusik verwenden',
    'text_filesel_context_delete_file': 'Loeschen',
    'mdesc_filesel_context_delete_file': 'Gewaehlte Datei loeschen',
    'text_filesel_context_delete_srm': 'Save loeschen',
    'mdesc_filesel_context_delete_srm': 'SRM-Save fuer diese ROM loeschen',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Cheats aus der YAML-Datei ansehen oder umschalten',
    'text_filesel_context_gameinfo': 'Spielinfo',
    'mdesc_filesel_context_gameinfo': 'Cover, Screenshot und Infos zu diesem Spiel vor dem Start anzeigen',
    'text_cheat_yes': 'Ja ',
    'text_cheat_no': 'Nein',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Name',
    'text_cheat_none_msg': 'Keine Cheats fuer diese ROM',
    'text_confirm_delete_file': 'Diese Datei loeschen?',
    'text_confirm_delete_srm': 'Save-Datei loeschen?',
    'text_confirm_hint': 'A:Bestaet.  B:Abbruch',
    'text_confirm_no_sel': '[Nein]',
    'text_confirm_no_unsel': 'Nein ',
    'text_confirm_yes_sel': '[Ja]',
    'text_confirm_yes_unsel': ' Ja ',
    'text_statusbar_play': 'A:Spielen B:Zurueck X:Menue',
    'text_statusbar_keys': 'A:OK B:Zurueck X:Menue Y:Kontext',
    'text_statusbar_spc': 'B:Zurueck',
    'text_statusbar_menu': 'A:OK B:Zurueck',
    'text_last': 'Letzte Spiele',
    'text_favorite': 'Favoriten',
    'text_no_last': 'Keine letzten',
    'text_no_favorite': 'Keine Favoriten',
    'text_favorites_full': 'Favoritenliste voll',
    'text_err_supplfile': 'Datei nicht gefunden:',
    'text_err_noimpl': 'Nicht unterstuetzt:',
    'text_err_nohw': 'Nur mit Mk.III-Hardware:',
    'text_err_generic': 'Ladefehler:',
    'text_on_p1': 'Ein: P1',
    'text_on_p2': 'Ein: P2',
    'text_on': 'Ein',
    'text_off': 'Aus',
    'text_15_max': '15 (max)',
    'text_theme': 'Thema',
    'text_cover_large': 'Gross',
    'text_cover_small': 'Klein',
    'text_gameinfo_context': 'Kontext',
    'text_nav_folder': 'Ordner',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Dauer',
    'text_enabled': 'Aktiv',
    'text_disabled': 'Inaktiv',
    'text_normal': 'Normal',
    'text_fast': 'Schnell',
    'text_a26_w256': '256 (breit)',
    'text_rtc': 'Echtzeit',
    'text_custom': 'Eigene',
    'text_yes': 'Ja',
    'text_no': 'Nein',
    'text_auto': 'Auto',
    'text_add': 'Hinzuf.',
    'text_remove': 'Entfern.',
    'text_edit': 'Aendern',
    'text_save': 'Speichern',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 Stunde',
    'text_spcplay': 'SPC-Player',
    'text_spcload': 'Lade SPC in SPC700{127}{128}        ',
    'text_spcstarta': '**** Spiele SPC ****',
    'text_spcstartb': 'Name:  ',
    'text_spcstartc': 'Song:  ',
    'text_spcstartd': 'Artist:',
    'text_spc_statusbar': 'B:Zurueck',
    'text_loading': 'Lade{127}{128}                            ',
    'text_saving': 'Speichere{127}{128}                      ',
    'text_cheat': 'Cheats fuer ',
    'text_cheat_noname': '(kein Name)',
    'text_igm_cheat_noname': '(kein Name)',
    'text_igm_ch_none': 'Keine Cheats',
    'text_igm_ft_tab': '<>:TAB L/R:ENDEN A:OEFFNEN SEL:HILFE B:ZU',
    'text_igm_ft_cheats': 'A:AN/AUS Y:AENDERN SEL:NEU X:CHEATS B:ZURUECK',
    'text_igm_ft_generic': 'A:WAEHLEN B:ZURUECK',
    'text_igm_master_on': 'CHEATS: AN',
    'text_igm_master_off': 'CHEATS: AUS',
    'text_igm_ft_ce_edit': 'A:AENDERN SEL:+CODE Y:ENTFERNEN B:ZURUECK',
    'text_igm_ft_ce_kbd': 'A:TIPPEN Y:LOESCHEN SEL:LEER X:OK B:ABBRUCH',
    'text_igm_ft_help': 'B:ZURUECK START:ZU',
    'text_igm_ce_title_new': 'NEUER CHEAT',
    'text_igm_ce_title_edit': 'CHEAT BEARBEITEN',
    'text_igm_ce_name': 'Name:',
    'text_igm_ce_save': 'SPEICHERN',
    'text_igm_ce_delete': 'CHEAT LÖSCHEN',
    'text_igm_ce_confirm': 'Diesen Cheat löschen?',
    'text_igm_ce_confirm_keys': 'A: ja   B: nein',
    'text_igm_ce_nosup': 'Bitte Firmware aktualisieren',
    'text_igm_ce_full': 'Die Cheat-Liste ist voll',
    'text_igm_ce_badcode': 'Ungültiger Code',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Firmware-Version: {2}',
    'text_si_busy': 'Berechne Speicherplatz{127}{128}',
    'text_si_removed': '    *** SD entfernt/USB belegt ***',
    'text_si_maker': 'SD Hersteller:   0x{3}, {34}{4}{34}',
    'text_si_product': 'SD Produktname: {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'SD Seriennr.:   {8}, Herst. {9}/{10}',
    'text_si_acc': 'SD Zugriff:  {11}.{12} / {13}.{14} ms avg/max',
    'text_si_accmeas': 'SD Zugriff:  messe{127}{128}',
    'text_si_usage': 'SD Nutzung: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'pruefe{127}{128}',
    'text_si_sgb_missing': 'fehlt',
    'text_si_sgb_mismatch': 'falsch',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'CIC Status: {19}',
    'text_si_clk': 'SNES Takt: {20}Hz',
    'text_si_clkmeas': 'SNES Takt: messe{127}{128}',
    'text_si_u16on': 'Ultra16 Seriennr. {21} (Autoboot Ein)',
    'text_si_u16off': 'Ultra16 Seriennr. {21} (Autoboot Aus)',
    'text_si_model': 'Modell: {22}',
    'text_si_updatefw': '*** Firmware aktualisieren ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Speichertest',
    'mdesc_mm_memtest': 'Prüft die Verbindungen FPGA-RAM (10 s). Der Komplettest prüft jede Zelle (30 s). Neustart.',
    'text_mtl_prompt': 'A: Leitungen  X: Komplett  B: Zurück',
    'text_mtl_prompt2': 'Beide starten neu. X dauert 30s.',
    'text_mtl_run': 'Teste Speicher, bitte warten{127}{128}',
    'text_mtl_none': 'Noch kein Test durchgeführt.',
    'text_mtl_pass': 'Alle RAM-Leitungen OK.',
    'text_mtl_fail': 'Fehler gefunden:',
    'text_mtl_nocore': '/sd2snes/fpga_test fehlt/defekt.',
    'text_mtl_more': '(weitere Fehler nicht gezeigt)',
    'text_mtl_cellpass': 'Alle Zellen geprüft.',
    'text_mtl_cellfail': 'Erste defekte Zelle bei 0x',
    'text_mtl_cellskip': 'Zellentest entfällt: erst Leitungen.',
    'text_mt_data': 'prüfe Datenleitung D',
    'text_mt_addr': 'prüfe Adressleitung A',
    'text_mt_short': 'evtl. Kurzschluss A',
    'text_mt_bytesel': 'prüfe LB# / UB#',
    'text_mt_ctrl': 'prüfe CE# / OE# / WE#',
    'text_mt_fpgactrl': 'prüfe FPGA CE# / OE# / WE#',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'PCM-Player',
    'text_pcm_prompt': 'A: Play/Pause   B: Schließen',
    'text_pcm_promptb': 'B: Schließen',
    'text_pcm_paused': 'Pausiert',
    'text_pcm_erropen': 'Datei kann nicht gelesen werden.',
    'text_pcm_errmagic': 'Keine MSU-1-PCM-Datei.',
    'text_pcm_nosup': '*** Bitte Firmware aktualisieren ***',
    'text_st_slotb_title': 'Sufami Turbo - Slot B',
    'text_st_slotb_footer': 'A:Start  B:Zurueck  <>:Seite  LR:Enden',
    'text_st_slotb_none': '[Kein Modul in Slot B]',
    'text_ips_nopatch': '[Kein Patch]',
    'text_ips_header': 'Patches',
    'mtext_patch_verify': 'Integritaet pruefen (~23s)',
    'mtext_patch_clearppu': 'PPU beim Start loeschen',
    'mdesc_patch_verify': 'Gepatchte ROM zum Pruefen erneut lesen (deutlich langsamer)',
    'mdesc_patch_clearppu': 'VRAM/CGRAM/OAM vor dem Start einer gepatchten ROM loeschen (Romhacks ohne PPU-Init)',
    'text_patch_hdr_auto': 'Auto  ',
    'text_patch_hdr_on': 'Header',
    'text_patch_hdr_off': 'Roh   ',
    'text_patch_footer': 'A:Start  Y:Mehr  B:Zurueck  <>:Seite  LR:Enden',
    'text_patch_creating': 'Erstelle gepatchte ROM...',
    'text_err_patchexport': 'Schreiben fehlgeschlagen',
    'text_patch_export_ok': 'Gepatchte ROM erstellt',
    'text_patch_export_part': 'ROM ok, Assets unvollstaendig',
    'text_patch_export_exists': 'Gepatchte ROM existiert',
    'text_patch_hdrsel_auto': 'Auto (erkennen)',
    'text_patch_hdrsel_on': 'Mit Header',
    'text_patch_hdrsel_off': 'Ohne Header',
    'mtext_patch_header_mode': 'Header-Modus',
    'mdesc_patch_header_mode': 'Wie die IPS-Offsets gelesen werden: Auto, Header (512 B Versatz) oder Roh.',
    'mtext_patch_create_rom': 'Gepatchte ROM erstellen',
    'mdesc_patch_create_rom': 'Schreibt die gepatchte ROM neben das Original und kopiert Cover, Spielstaende, Cheats und Anleitungen mit. Kann mehrere Minuten dauern.',
    'cheat_tab_head': 'Name                                     Aktiv',
    'cheat_tab_hint_text': ' A:Ein/Aus Y:Bearb. Sel:Neu B:Ende',
    'mtext_browser_showcov': 'Cover anzeigen',
    'mdesc_browser_showcov': 'Spielcover im Menue anzeigen',
    'mtext_browser_covlists': ' {129}Favoriten/Letzte',
    'mdesc_browser_covlists': 'Cover auch in Letzte/Favoriten anzeigen',
    'mtext_browser_menumusic': 'Menue-Musik',
    'mtext_browser_menumusic_random': ' {129}Zufällige Musik',
    'mtext_browser_menusfx': 'Menue-Sounds',
    'mtext_browser_text_outline': 'Textkontur',
    'mtext_browser_text_aa': 'Textkantenglättung',
    'mdesc_browser_menumusic': 'Hintergrundmusik (menu.spc) im Menue spielen',
    'mtext_browser_sortfav': 'Favoriten sortieren',
    'mdesc_browser_sortfav': 'Favoritenliste alphabetisch sortieren',
    'mtext_browser_restoretheme': 'Theme zuruecksetzen',
    'mdesc_browser_restoretheme': 'Menue-Theme auf Standard zuruecksetzen',
    'mtext_browser_restoreclassic': 'Klassisches Theme laden',
    'mdesc_browser_restoreclassic': 'Klassisches sd2snes-Aussehen laden (benoetigt /sd2snes/classic.thm auf der Karte)',
    'mtext_browser_restoremusic': 'Musik zuruecksetzen',
    'mdesc_browser_restoremusic': 'Menue-Musik auf Standard zuruecksetzen (menu.spc)',
    'mdesc_browser_menumusic_random': 'Bei jedem Laden eine zufällige .spc aus dem Ordner',
    'mdesc_browser_text_outline': 'Dunkle Kontur am Menütext: dem Thema folgen oder erzwingen',
    'mdesc_browser_text_aa': 'Weiche Kanten am Menütext: dem Thema folgen oder erzwingen',
    'text_mm_language': 'Sprache',
    'mdesc_mm_language': 'Sprache fuer Menue/Firmware setzen',
    'mdesc_browser_menusfx': 'Soundeffekte beim Navigieren durch das Menü abspielen',
    'mtext_browser_gameinfo': 'Spielinfo',
    'mtext_gameinfo_enable': 'Infoseite anzeigen',
    'mdesc_browser_gameinfo': 'Cover, Screenshot und Infos vor dem Start einer ROM mit /sd2snes/info-Eintrag anzeigen',
    'mdesc_cfg_gameinfo': 'Optionen der Spielinfo-Seite (vor dem Start)',
    'mtext_browser_gameinfo_video': ' {129}Video zeigen',
    'mdesc_browser_gameinfo_video': 'Animierten Clip in der Spielinfo abspielen (aus: statisches Standbild)',
    'mtext_browser_gameinfo_music': ' {129}Videomusik',
    'mdesc_browser_gameinfo_music': 'Videomusik abspielen, während der Clip läuft. Benötigt Video zeigen.',
    'text_gi_developer': 'Entwickler',
    'text_gi_publisher': 'Publisher',
    'text_gi_year': 'Jahr',
    'text_gi_players': 'Spieler',
    'text_gi_genre': 'Genre',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Start  B: Zurück  Y: Beschreibung',
    'text_gi_footer_nav': 'A:Start B:Zurück Y:Besch Ho/Ru:Spiel',
    'text_gi_footer_full': 'B: Zurück  Hoch/Runter: Scrollen',
    'text_gi_footer_man': 'A: Start  B: Zurück  Y: Beschreibung  X: Guides',
    'text_gi_footer_nav_man': 'A:Start B:Zurück Y:Besch X:Guides Ho/Ru:Spiel',
    'text_gi_footer_pick': 'A: Lesen  B: Zurück',
    'text_gi_slug_manual': 'Handbuch',
    'text_gi_slug_guide': 'Anleitung',
    'text_gi_slug_map': 'Karte',
    'text_gi_slug_insert': 'Beilage',
    'text_gi_slug_other': 'Sonstiges',
}
