"""Translated strings for the sd2snes menu. Translate each value.

Pre-seeded with the English source. Any label left in English (or removed)
falls back to English at build time. {129}=submenu icon, {127}{128}=ellipsis.
Accented chars (á é í ó ú ñ ü ¿ ¡ ...) may be written as real UTF-8.

Russian: the font carries the full modern alphabet (33+33 letters). What it does
NOT carry is the stress mark or the letters of the other Cyrillic languages
(І Ї Є Ў Ґ) -- those would fall through as raw UTF-8 and draw garbage, so keep
the text to Russian proper. 'ё' is a real glyph here, no need to spell it 'е'.
"""

TRANSLATIONS = {
    'text_clkset': 'Установите время',
    'text_mainmenu': 'Главное меню',
    'text_mm_file': 'Файлы',
    'text_mm_last': 'Недавние игры',
    'text_mm_favorites': 'Избранные игры',
    'text_igm_hdr_controls': 'УПРАВЛЕНИЕ В ИГРЕ',
    'text_igm_open': 'Меню:           L+R+Y+Влево',
    'text_igm_save': 'Сохранить:      Start+R',
    'text_igm_load': 'Загрузить:      Start+L',
    'text_igm_slot': 'Выбор слота:    Select + D-Pad',
    'text_igm_reset': 'Выход в меню:   L+R+Select+X',
    'text_igm_hdr_keys': 'КЛАВИШИ МЕНЮ',
    'text_igm_tab': 'L / R:      вкладка',
    'text_igm_page': 'Влево/Вправо: страница',
    'text_igm_nav': 'Вверх/Вниз: выбор',
    'text_igm_act': 'A: применить  X: все',
    'text_igm_close': 'B: закрыть меню',
    'text_igm_note': 'Часть комбинаций задаётся в настройках',
    'text_igm_st_title': 'ВЫБОР СЛОТА СОСТОЯНИЯ',
    'text_igm_st_slot': 'СЛОТ',
    'text_igm_st_full': 'ЗАНЯТ',
    'text_igm_st_empty': 'ПУСТО',
    'text_igm_st_hint': 'Start+R запись  Start+L чтение',
    'text_igm_st_disabled': 'Слоты состояний отключены',
    'text_igm_tab_cheats': 'ЧИТЫ',
    'text_igm_tab_states': 'СОСТОЯНИЯ',
    'text_igm_tab_saves': 'СОХРАНЕНИЯ',
    'text_igm_tab_help': 'СПРАВКА',
    'text_igm_tab_manual': 'ГАЙДЫ',
    'text_igm_tab_trainer': 'ТРЕЙНЕР',
    'text_igm_sv_title': 'СОХРАНЕНИЕ ИГРЫ',
    'text_igm_sv_nosram': 'В этой игре нет сохранения с батарейкой',
    'text_igm_sv_file': 'Файл .srm:',
    'text_igm_sv_exists': 'ЕСТЬ',
    'text_igm_sv_missing': 'НЕТ',
    'text_igm_sv_size': 'Размер:',
    'text_igm_sv_write': 'Запись:',
    'text_igm_sv_autosave': 'Автосейв:',
    'text_igm_sv_on': 'ВКЛ',
    'text_igm_sv_off': 'ВЫКЛ',
    'text_igm_sv_hint_on': 'Сохранение пишется автоматически во время игры',
    'text_igm_sv_hint_off': 'Автосохранение выключено - сохраняйте из игры',
    'text_igm_sv_slottitle': 'ВЫБОР СЛОТА SRAM',
    'text_igm_sv_slot': 'СЛОТ',
    'text_igm_sv_slothint': 'Применится при следующем запуске игры',
    'text_igm_mn_title': 'РУКОВОДСТВО К ИГРЕ',
    'text_igm_mn_read': 'A: Читать руководство',
    'text_igm_mn_pages': 'стр.',
    'text_igm_mn_notfound': 'Руководство не найдено',
    'text_igm_mn_error': 'Ошибка загрузки руководства',
    'text_igm_mn_guide': 'ГАЙД',
    'text_igm_mn_select': 'ВЫБЕРИТЕ ГАЙД',
    'text_igm_mn_keys1': 'A: зум 2x   L/R: страница',
    'text_igm_mn_keys2': 'D-Pad: сдвиг   B: назад',
    'text_igm_mn_slug_manual': 'Руководство',
    'text_igm_mn_slug_guide': 'Гайд',
    'text_igm_mn_slug_map': 'Карта',
    'text_igm_mn_slug_insert': 'Вкладыш',
    'text_igm_mn_slug_other': 'Другое',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'ТРЕЙНЕР ПАМЯТИ',
    'text_igm_tr_searchtype': 'Тип поиска:',
    'text_igm_tr_datatype': 'Разрядность:',
    'text_igm_tr_value': 'Значение:',
    'text_igm_tr_candidates': 'Кандидаты:',
    'text_igm_tr_compare': 'Сравнение:',
    'text_igm_tr_exact': 'Точное',
    'text_igm_tr_unknown': 'Неизвестно',
    'text_igm_tr_8bit': '8 бит',
    'text_igm_tr_16bit': '16 бит',
    'text_igm_tr_eq': 'Равно',
    'text_igm_tr_ne': 'Не равно',
    'text_igm_tr_changed': 'Менялось',
    'text_igm_tr_unchanged': 'Не менялось',
    'text_igm_tr_increased': 'Выросло',
    'text_igm_tr_decreased': 'Упало',
    'text_igm_tr_gt': 'Больше',
    'text_igm_tr_lt': 'Меньше',
    'text_igm_tr_newsearch': 'НОВЫЙ ПОИСК',
    'text_igm_tr_filter': 'ФИЛЬТР',
    'text_igm_tr_results': 'РЕЗУЛЬТАТЫ',
    'text_igm_tr_reset': 'СБРОС ПОИСКА',
    'text_igm_tr_address': 'АДРЕС',
    'text_igm_tr_current': 'ТЕКУЩЕЕ',
    'text_igm_tr_setvalue': 'ЗАПИСАТЬ',
    'text_igm_tr_freeze': 'ЗАМОРОЗИТЬ',
    'text_igm_tr_unfreeze': 'РАЗМОРОЗИТЬ',
    'text_igm_tr_addcheat': 'ДОБАВИТЬ В ЧИТЫ',
    'text_igm_tr_frozen': 'ЗАМОРОЖЕНО',
    'text_igm_tr_searching': 'Поиск...',
    'text_igm_tr_noresults': 'Нет результатов',
    'text_igm_tr_toomany': 'Слишком много - фильтруйте ещё',
    'text_igm_tr_dropped_ss': 'Поиск сброшен - состояние загружено',
    'text_igm_tr_dropped_rst': 'Поиск сброшен - сброс консоли',
    'text_igm_tr_nofreeze': 'Нет места для заморозки',
    'text_igm_tr_hint_setup': 'A: выбрать   D-Pad: менять',
    'text_igm_tr_hint_edit': 'D-Pad: править   A: OK   B: выход',
    'text_igm_tr_hint_list': 'A: смотреть   B: назад',
    'text_igm_tr_master_off': 'Мастер читов ВЫКЛ',
    'mtext_mm_cfg': 'Настройки',
    'mtext_mm_sysinfo': 'Сведения о системе',
    'mtext_cfg_time': 'Установка часов',
    'mtext_cfg_ask_clock': 'Спрашивать время при старте',
    'mtext_cfg_bsx': 'Настройки BS-X',
    'mtext_cfg_browser': 'Настройки браузера',
    'mtext_cfg_chip': 'Параметры чипов',
    'mtext_cfg_sgb': 'Настройки SGB',
    'mtext_cfg_ingame': 'Настройки в игре',
    'mtext_cfg_savestates': 'Настройки состояний',
    'mtext_cfg_scic': 'Настройки SuperCIC',
    'mtext_cfg_patch': 'Параметры патчей',
    'mtext_bsx_timesource': 'Часы BS-X',
    'mtext_bsx_time': 'Своё время',
    'mtext_scic_enable': 'Включить SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Видеорежим меню',
    'mtext_scic_vmode_game': ' {129}Видеорежим игры',
    'mtext_scic_buscompat': 'Совместимость шины',
    'mtext_browser_sort': 'Сортировать папки',
    'mtext_browser_hide_ext': 'Скрывать расширения',
    'mtext_browser_msu_folders': 'Папки MSU-1 открывать как игру',
    'mtext_browser_sd2snes_dir': 'Показывать папку sd2snes',
    'mtext_browser_screensaver': 'Заставка',
    'mtext_browser_screensaver_timeout': 'Затухание экрана через',
    'mtext_browser_ledbright': 'Яркость светодиодов',
    'mtext_ingame_cheats': 'Запускать с включёнными читами',
    'mtext_ingame_shortreset': 'Сброс в меню',
    'mtext_ingame_enable': 'Перехват в игре',
    'mtext_ingame_buttons': ' {129}Кнопки в игре',
    'mtext_ingame_cheat_overlay': ' {129}Меню в игре',
    'mtext_ingame_game_manual': ' {129}Руководство к игре',
    'mtext_ingame_holdoff': ' {129}Задержка запуска',
    'mtext_ingame_savestate': 'Состояния в игре',
    'mtext_savestate_slots': ' {129}Слоты состояний',
    'mtext_loadstate_delay': ' {129}Задержка загрузки (кадры)',
    'mtext_sgb_enable_hooks': 'Перехваты в игре',
    'mtext_sgb_enable_state': 'Состояния (XR, XL)',
    'mtext_sgb_enh_override': 'Возможности SGB',
    'mtext_sgb_spr_increase': 'Предел спрайтов (40)',
    'mtext_sgb_volume_boost': 'Усиление громкости',
    'mtext_sgb_clock': 'Тактовая частота',
    'mtext_sgb_bios': 'Версия BIOS',
    'mtext_ingame_regionpatch': 'Автопатч региона',
    'mtext_ingame_1chiptransientfixes': 'Правки для 1CHIP',
    'mtext_ingame_brightlimit': 'Предел яркости',
    'mtext_ingame_resetpatch': 'Патч сброса для фазы часов',
    'mtext_ingame_autosave': 'Автосохранение',
    'mtext_ingame_autosave_msu1': ' {129}Автосохранение MSU-1',
    'mtext_chip_cx4_speed': 'Скорость Cx4',
    'mtext_chip_cc_time_limit': 'Таймер Competition Cart (мин)',
    'mtext_chip_gsu_speed': 'Скорость SuperFX',
    'mtext_chip_msu1_volume_boost': 'Усиление громкости MSU-1',
    'mtext_a26_width': 'Ширина картинки Atari 2600',
    'mdesc_mm_last': 'Показывать до 10 недавно запущенных игр',
    'mdesc_mm_favorites': 'Показывать до 20 избранных игр',
    'mdesc_mm_cfg': 'Настройка sd2snes',
    'mdesc_mm_sysinfo': 'Сведения о прошивке, SD-карте, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Установить дату и время',
    'mdesc_cfg_ask_clock': 'Спрашивает время при старте, пока часы не настроены',
    'mdesc_cfg_bsx': 'Настройки, относящиеся к BS-X/Satellaview',
    'mdesc_cfg_browser': 'Изменить настройки файлового браузера',
    'mdesc_cfg_chip': 'Настроить возможности спецчипов',
    'mdesc_cfg_ingame': 'Настроить возможности в игре',
    'mdesc_cfg_sgb': 'Настроить возможности Super Game Boy',
    'mdesc_cfg_savestates': 'Настроить сохранение состояний',
    'mdesc_cfg_scic': 'Включить SuperCIC и задать видеорежимы',
    'mdesc_cfg_patch': 'Параметры мягкого патчинга IPS/BPS',
    'mdesc_bsx_timesource': 'Какую дату и время увидят игры BS-X',
    'mdesc_bsx_time': 'Задать своё время и дату для игр BS-X',
    'mdesc_scic_enable': 'Нужно для расширенных возможностей SuperCIC',
    'mdesc_scic_vmode_menu': 'Видеорежим для меню',
    'mdesc_scic_vmode_game': 'Видеорежим для игр',
    'mdesc_scic_buscompat': 'Узкие тайминги шины картриджа для консолей, где часть игр зависает или глючит. Включайте, только если видите зависания.',
    'mdesc_browser_sort': 'Сортировать ли списки файлов',
    'mdesc_browser_hide_ext': 'Скрывать ли расширения файлов',
    'mdesc_browser_msu_folders': 'A на папке, где только один ROM MSU-1, открывает игру',
    'mdesc_browser_sd2snes_dir': 'Показывать /sd2snes в списке файлов',
    'mdesc_browser_screensaver': 'Затухание экрана через некоторое время',
    'mdesc_browser_screensaver_timeout': 'Через какое время будет затухание экрана',
    'mdesc_browser_ledbright': 'Изменить яркость светодиодов',
    'mdesc_ingame_cheats': 'Запускать ли игру с включёнными читами. Можно менять кнопками в игре',
    'mdesc_ingame_shortreset': 'Куда ведёт сброс. Папка/ROM открывают папку последней игры. Длительность: короткое нажатие сбрасывает игру, долгое ведёт к ROMу.',
    'mdesc_ingame_enable': 'Нужно для кнопок в игре и читов 7E/7F',
    'mdesc_ingame_buttons': 'Кнопки в игре (сброс, вкл/выкл читов{127}{128}). Требуется перехват в игре.',
    'mdesc_ingame_cheat_overlay': 'Меню в игре (удерживайте L+R+Y+Влево): читы, состояния, сохранения и гайды. Нужен перехват. Недоступно в некоторых играх со спецчипами.',
    'mdesc_ingame_game_manual': 'Показывать руководство в меню в игре. Нужен файл <rom>.man в /sd2snes/info.',
    'mdesc_ingame_holdoff': 'Ждать 10 секунд перед включением перехвата (помогает части игр загрузиться)',
    'mdesc_ingame_savestate': 'Включить состояния в игре и выбрать контроллер. По умолчанию: запись - Start+R, чтение - Start+L',
    'mdesc_savestate_slots': 'Включить слоты состояний. Select + D-Pad: каждое направление - свой слот',
    'mdesc_loadstate_delay': 'Настроить задержку загрузки состояния (кадры)',
    'mdesc_sgb_enable_hooks': 'Нужно для кнопок в игре',
    'mdesc_sgb_enable_state': 'Встроенные сохранения состояний на SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Включить или выключить улучшения SGB',
    'mdesc_sgb_spr_increase': 'Увеличить число видимых спрайтов',
    'mdesc_sgb_volume_boost': 'Усилить звук SGB, если он слишком тихий',
    'mdesc_sgb_clock': 'Установка тактовой частоты SGB',
    'mdesc_sgb_bios': 'Выбрать версию прошивки/BIOS для SGB',
    'mdesc_ingame_regionpatch': 'Обходить простую региональную защиту игр',
    'mdesc_ingame_1chiptransientfixes': 'Патчить смену яркости, чтобы убрать срывы синхронизации, гаснущие строки и пропажу тени на консолях 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Ограничить общую яркость (например, на 1CHIP для уровней RGB)',
    'mdesc_ingame_resetpatch': 'Патч сброса для выравнивания тактов. Убирает графические сбои в части игр',
    'mdesc_ingame_autosave': 'Записывать файл SRM автоматически при изменении Save RAM',
    'mdesc_ingame_autosave_msu1': 'MSU-1: сохранять SRM при удобном случае. Возможны короткие подтормаживания.',
    'mdesc_chip_cx4_speed': 'Скорость программного ядра Cx4',
    'mdesc_chip_cc_time_limit': "Таймер раунда Campus Challenge '92 / PowerFest '94",
    'mdesc_chip_gsu_speed': 'Скорость программного ядра SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Усилить звук MSU1, если ваш sd2snes слишком тихий (Rev. E-G)',
    'mdesc_a26_width': 'Ширина картинки Atari 2600: 160 - родная 1:1, 256 - на весь экран',
    'mdesc_cx4_speed_fast': 'Работать как можно быстрее',
    'mdesc_cx4_speed_normal': 'Работать примерно с исходной скоростью',
    'mdesc_gsu_speed_fast': 'Работать как можно быстрее',
    'mdesc_gsu_speed_normal': 'Работать примерно с исходной скоростью',
    'text_filesel_selected_file': 'Выбранный файл',
    'text_filesel_context_add_to_favorites': 'В избранное',
    'mdesc_filesel_context_add_to_favorites': 'Добавить выбранный файл в избранное',
    'text_filesel_context_remove_from_favorites': 'Убрать из избранного',
    'mdesc_filesel_context_remove_from_favorites': 'Убрать выбранный файл из избранного',
    'text_recent_context_remove_from_recent': 'Убрать из недавних',
    'mdesc_recent_context_remove_from_recent': 'Убрать выбранный файл из списка недавних игр',
    'text_filesel_set_as_autoboot': 'Автозапуск',
    'mdesc_filesel_set_as_autoboot': 'Запускать этот ROM при включении приставки (удерживайте START при включении или сбросе, чтобы отменить)',
    'text_filesel_set_as_bgm': 'Музыка меню',
    'mdesc_filesel_set_as_bgm': 'Использовать этот SPC как фоновую музыку меню',
    'text_filesel_context_delete_file': 'Удалить',
    'mdesc_filesel_context_delete_file': 'Удалить выбранный файл',
    'text_filesel_context_delete_srm': 'Удалить сохранение',
    'mdesc_filesel_context_delete_srm': 'Удалить файл сохранения SRM для этого ROMа',
    'text_filesel_context_cheats': 'Читы',
    'mdesc_filesel_context_cheats': 'Просмотр и включение читов из файла YAML этого ROMа',
    'text_filesel_context_gameinfo': 'Об игре',
    'mdesc_filesel_context_gameinfo': 'Показать экран об игре (обложка, снимок и сведения) перед запуском',
    'text_cheat_yes': 'Да  ',
    'text_cheat_no': 'Нет ',
    'text_cheat_none_title': 'Читы',
    'text_ce_name': 'Имя',
    'text_cheat_none_msg': 'Читы для этого ROMа не найдены',
    'text_confirm_delete_file': 'Удалить этот файл?',
    'text_confirm_delete_srm': 'Удалить файл сохранения?',
    'text_confirm_hint': 'A:Подтвердить  B:Отмена',
    'text_confirm_no_sel': '[Нет]',
    'text_confirm_no_unsel': ' Нет ',
    'text_confirm_yes_sel': '[Да]',
    'text_confirm_yes_unsel': ' Да ',
    'text_statusbar_play': 'A:Играть B:Назад X:Меню',
    'text_statusbar_keys': 'A:Выбор B:Назад X:Меню Y:Контекст',
    'text_statusbar_spc': 'B:Назад',
    'text_statusbar_menu': 'A:Выбор B:Назад',
    'text_last': 'Недавние игры',
    'text_favorite': 'Избранные игры',
    'text_no_last': 'Нет недавних игр',
    'text_no_favorite': 'Нет избранных игр',
    'text_favorites_full': 'Список избранного полон',
    'text_err_supplfile': 'Файл не найден:',
    'text_err_noimpl': 'Чип не поддерживается:',
    'text_err_nohw': 'Нужна плата Mk.III:',
    'text_err_generic': 'Ошибка загрузки:',
    'text_on_p1': 'Вкл: P1',
    'text_on_p2': 'Вкл: P2',
    'text_on': 'Вкл',
    'text_off': 'Выкл',
    'text_15_max': '15 (макс)',
    'text_theme': 'Тема',
    'text_cover_large': 'Крупно',
    'text_cover_small': 'Мелко',
    'text_gameinfo_context': 'Контекст',
    'text_nav_folder': 'Папка',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Длительность',
    'text_enabled': 'Включено',
    'text_disabled': 'Выключено',
    'text_normal': 'Обычная',
    'text_fast': 'Быстрая',
    'text_a26_w256': '256 (широкая)',
    'text_rtc': 'Реальное',
    'text_custom': 'Своё',
    'text_yes': 'Да',
    'text_no': 'Нет',
    'text_auto': 'Авто',
    'text_add': 'Добавить',
    'text_remove': 'Убрать',
    'text_edit': 'Изменить',
    'text_save': 'Сохранить',
    'text_1min': '1 мин',
    'text_2min': '2 мин',
    'text_3min': '3 мин',
    'text_4min': '4 мин',
    'text_5min': '5 мин',
    'text_10min': '10 мин',
    'text_15min': '15 мин',
    'text_20min': '20 мин',
    'text_30min': '30 мин',
    'text_45min': '45 мин',
    'text_60min': '1 час',
    'text_spcplay': 'Плеер SPC',
    'text_spcload': 'Загрузка SPC в SPC700{127}{128}',
    'text_spcstarta': '**** Сейчас играет SPC ****',
    'text_spcstartb': 'Имя:   ',
    'text_spcstartc': 'Трек:  ',
    'text_spcstartd': 'Автор: ',
    'text_spc_statusbar': 'B:Назад',
    'text_loading': 'Загрузка{127}{128}                       ',
    'text_saving': 'Запись{127}{128}                         ',
    'text_cheat': 'Читы для ',
    'text_cheat_noname': '(без имени)',
    'text_igm_cheat_noname': '(без имени)',
    'text_igm_ch_none': 'Нет читов',
    'text_igm_ft_tab': '<>:ВКЛАДКА L/R:КРАЯ A:ОТКРЫТЬ B:ЗАКРЫТЬ',
    'text_igm_ft_cheats': 'A:ВКЛ/ВЫКЛ Y:ПРАВКА SEL:НОВЫЙ X:ЧИТЫ B:НАЗАД',
    'text_igm_ft_generic': 'A:ВЫБРАТЬ B:НАЗАД',
    'text_igm_master_on': 'ЧИТЫ: ВКЛ',
    'text_igm_master_off': 'ЧИТЫ: ВЫКЛ',
    'text_igm_ft_ce_edit': 'A:ПРАВКА SEL:+КОД Y:УБРАТЬ B:НАЗАД',
    'text_igm_ft_ce_kbd': 'A:ВВОД Y:СТЕРЕТЬ SEL:ПРОБЕЛ X:OK B:ОТМЕНА',
    'text_igm_ce_title_new': 'НОВЫЙ ЧИТ',
    'text_igm_ce_title_edit': 'ИЗМЕНИТЬ ЧИТ',
    'text_igm_ce_name': 'Имя:',
    'text_igm_ce_save': 'СОХРАНИТЬ',
    'text_igm_ce_delete': 'УДАЛИТЬ ЧИТ',
    'text_igm_ce_confirm': 'Удалить этот чит?',
    'text_igm_ce_confirm_keys': 'A: да   B: нет',
    'text_igm_ce_nosup': 'Обновите прошивку',
    'text_igm_ce_full': 'Список читов заполнен',
    'text_igm_ce_badcode': 'Неверный код',
    'text_si_fw': '    Версия прошивки: {2}',
    'text_si_busy': 'Подсчёт места на карте{127}{128}',
    'text_si_removed': '   *** SD извлечена / USB занят ***',
    'text_si_maker': 'Изготовитель SD: 0x{3}, {34}{4}{34}',
    'text_si_product': 'Название SD:     {34}{5}{34}, рев. {6}.{7}',
    'text_si_serial': 'Серийный SD:     {8}, вып. {9}/{10}',
    'text_si_acc': 'Доступ к SD: {11}.{12} / {13}.{14} мс ср/макс',
    'text_si_accmeas': 'Доступ к SD: измерение{127}{128}',
    'text_si_usage': 'Занято на карте: {15}МБ / {16}МБ',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'проверка{127}{128}',
    'text_si_sgb_missing': 'нет',
    'text_si_sgb_mismatch': 'не совпал',
    'text_si_sgb_ok': 'ок',
    'text_si_cic': 'Состояние CIC: {19}',
    'text_si_clk': 'Тактовая частота SNES: {20}Гц',
    'text_si_clkmeas': 'Тактовая частота SNES: измерение{127}{128}',
    'text_si_u16on': 'Ultra16 сер. {21} (автозапуск вкл)',
    'text_si_u16off': 'Ultra16 сер. {21} (автозапуск выкл)',
    'text_si_model': 'Модель: {22}',
    'text_si_updatefw': '*** Обновите прошивку ***',
    'mtext_mm_memtest': 'Тест памяти',
    'mdesc_mm_memtest': 'Проверяет связи FPGA и ОЗУ (10 с). Полный тест проверяет каждую ячейку (30 с). Консоль перезагрузится.',
    'text_mtl_prompt': 'A: Линии  X: Полный  B: Закрыть',
    'text_mtl_prompt2': 'Оба сбросят консоль. X займёт 30 с.',
    'text_mtl_run': 'Проверка памяти, подождите{127}{128}',
    'text_mtl_none': 'Тест ещё не запускался.',
    'text_mtl_pass': 'Все линии ОЗУ в порядке.',
    'text_mtl_fail': 'Найдены ошибки:',
    'text_mtl_nocore': '/sd2snes/fpga_test нет или повреждён.',
    'text_mtl_more': '(показаны не все ошибки)',
    'text_mtl_cellpass': 'Все ячейки проверены.',
    'text_mtl_cellfail': 'Первая сбойная ячейка: 0x',
    'text_mtl_cellskip': 'Тест ячеек пропущен: сначала линии.',
    'text_mt_data': 'линия данных D',
    'text_mt_addr': 'линия адреса A',
    'text_mt_short': 'возможно замыкание A',
    'text_mt_bytesel': 'проверьте LB# / UB#',
    'text_mt_ctrl': 'проверьте CE# / OE# / WE#',
    'text_mt_fpgactrl': 'FPGA: проверьте CE# / OE# / WE#',
    'text_pcm_title': 'Плеер PCM',
    'text_pcm_prompt': 'A: Пуск/Пауза   B: Закрыть',
    'text_pcm_promptb': 'B: Закрыть',
    'text_pcm_paused': 'Пауза',
    'text_pcm_erropen': 'Не удалось прочитать файл.',
    'text_pcm_errmagic': 'Это не PCM-файл MSU-1.',
    'text_pcm_nosup': '*** Обновите прошивку ***',
    'text_st_slotb_title': 'Sufami Turbo - слот B',
    'text_st_slotb_footer': 'A:Играть B:Назад <>:Стр. LR:Края',
    'text_st_slotb_none': '[В слоте B пусто]',
    'text_ips_nopatch': '[Без патча]',
    'text_ips_header': 'Патчи',
    'mtext_patch_verify': 'Проверка целостности (~23с)',
    'mtext_patch_clearppu': 'Очистка PPU при старте',
    'mdesc_patch_verify': 'Перечитать пропатченный ROM для проверки (загрузка намного дольше)',
    'mdesc_patch_clearppu': 'Очищать VRAM/CGRAM/OAM перед стартом пропатченного ROMа (для ромхаков без инициализации PPU)',
    'text_patch_hdr_auto': 'авто  ',
    'text_patch_hdr_on': 'загол.',
    'text_patch_hdr_off': 'сырой ',
    'text_patch_footer': 'A:Играть Y:Ещё B:Назад <>:Стр. LR:Края',
    'text_patch_creating': 'Создание пропатченного ROMа...',
    'text_err_patchexport': 'Не записать ROM',
    'text_patch_export_ok': 'Пропатченный ROM создан',
    'text_patch_export_part': 'ROM готов, данные неполны',
    'text_patch_export_exists': 'Такой ROM уже существует',
    'text_patch_hdrsel_auto': 'Авто (определить)',
    'text_patch_hdrsel_on': 'С заголовком',
    'text_patch_hdrsel_off': 'Без заголовка',
    'mtext_patch_header_mode': 'Режим заголовка',
    'mdesc_patch_header_mode': 'Как читаются смещения IPS: Авто, С заголовком (сдвиг 512 Б) или Без.',
    'mtext_patch_create_rom': 'Создать пропатченный ROM',
    'mdesc_patch_create_rom': 'Записать пропатченный ROM рядом с исходным, с именем патча, скопировав обложку, сохранения, читы и гайды. Займёт несколько минут.',
    'cheat_tab_head': 'Описание                                 Включён',
    'cheat_tab_hint_text': ' A:Вкл/Выкл Y:Изм Sel:Доб B:Назад ',
    'mtext_browser_showcov': 'Показывать обложки',
    'mdesc_browser_showcov': 'Показывать обложки игр в меню',
    'mtext_browser_covlists': ' {129}Избранное/недавние',
    'mdesc_browser_covlists': 'Показывать обложки и в списках недавних и избранных',
    'mtext_browser_menumusic': 'Музыка меню',
    'mtext_browser_menumusic_random': ' {129}Случайная музыка',
    'mtext_browser_menusfx': 'Звуки меню',
    'mtext_browser_text_outline': 'Контур текста',
    'mtext_browser_text_aa': 'Сглаживание текста',
    'mdesc_browser_menumusic': 'Играть фоновую музыку (menu.spc) в меню',
    'mtext_browser_sortfav': 'Сортировать избранное',
    'mdesc_browser_sortfav': 'Сортировать список избранного по алфавиту',
    'mtext_browser_restoretheme': 'Вернуть тему',
    'mdesc_browser_restoretheme': 'Вернуть встроенную тему меню',
    'mtext_browser_restoreclassic': 'Вернуть классическую тему',
    'mdesc_browser_restoreclassic': 'Загрузить классический вид sd2snes (нужен /sd2snes/classic.thm на карте)',
    'mtext_browser_restoremusic': 'Вернуть музыку',
    'mdesc_browser_restoremusic': 'Вернуть стандартную музыку меню (menu.spc)',
    'mdesc_browser_menumusic_random': 'Случайный .spc из папки музыки при каждой загрузке',
    'mdesc_browser_text_outline': 'Тёмный контур текста меню: следовать теме или задать',
    'mdesc_browser_text_aa': 'Мягкие края текста меню: следовать теме или задать',
    'text_mm_language': 'Язык',
    'mdesc_mm_language': 'Язык меню и прошивки',
    'mdesc_browser_menusfx': 'Звуковые эффекты при навигации по меню',
    'mtext_browser_gameinfo': 'Об игре',
    'mtext_gameinfo_enable': 'Показывать экран',
    'mdesc_browser_gameinfo': 'Показывать обложку, снимок и сведения перед запуском ROMа, у которого есть запись в /sd2snes/info',
    'mdesc_cfg_gameinfo': 'Параметры экрана об игре перед запуском',
    'mtext_browser_gameinfo_video': ' {129}Показывать видео',
    'mdesc_browser_gameinfo_video': 'Проигрывать ролик на экране об игре (выкл - статичный снимок)',
    'mtext_browser_gameinfo_music': ' {129}Музыка ролика',
    'mdesc_browser_gameinfo_music': 'Играть звук ролика, пока он идёт. Необходимо включить Показывать видео.',
    'text_gi_developer': 'Разработчик',
    'text_gi_publisher': 'Издатель',
    'text_gi_year': 'Год',
    'text_gi_players': 'Игроков',
    'text_gi_genre': 'Жанр',
    'text_gi_chip': 'Чип',
    'text_gi_footer': 'A: Играть   B: Назад   Y: Описание',
    'text_gi_footer_nav': 'A:Играть B:Назад Y:Описание Вверх/Вниз',
    'text_gi_footer_full': 'B: Назад   Вверх/Вниз: прокрутка',
    'text_gi_footer_man': 'A: Играть  B: Назад  Y: Описание  X: Гайды',
    'text_gi_footer_nav_man': 'A:Играть B:Назад Y:Опис. X:Гайды Вв/Вн',
    'text_gi_footer_pick': 'A: Открыть   B: Назад',
    'text_gi_slug_manual': 'Руководство',
    'text_gi_slug_guide': 'Гайд',
    'text_gi_slug_map': 'Карта',
    'text_gi_slug_insert': 'Вкладыш',
    'text_gi_slug_other': 'Другое',
}
