CORE = spc7110

VSRC = address.v cheat.v clk_test.v dac.v DCM_Scope.v main.v mcu_cmd.v msu.v sd_dma.v spc7110_bsram.v spi.v
VHSRC = SPC7110.vhd SPC7110Map.vhd SPC7110_DEC.vhd SPC7110_DEC_PKG.vhd SPC7110_FIFO.vhd SPC7110_MULDIV.vhd RTC4513.vhd

COMMON_IP = dac_buf msu_databuf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
